SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{62D7410A9D46207E}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{62D741081C4FB8F8}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B297752B585}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B29765366B7}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2896AEA994}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2FD8779B17}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2EC3530C21}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D13412A3751197}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D210807813C38A}" : "{E7D9069BE26B7A4C}Configs/EntityCatalog/UK/ACE_InventoryItems_EntityCatalog_Equipment_UK.conf" {
  }
 }
}