SCR_EntityCatalogMultiList {
 m_aMultiLists {
  ACE_EntityCatalogMultiListEntry "{69D247D5F3DF316A}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D247D5F0D5014E}" : "{E7D9069BE26B7A4C}Configs/EntityCatalog/UK/ACE_InventoryItems_EntityCatalog_Equipment_UK.conf" {
  }
 }
}