ActionManager {
 Actions {
  Action ACE_VerticalZeroingUp {
   Type AnalogRelative
   InputSource InputSourceSum "{68F803CCB717067B}" {
    Sources {
     InputSourceCombo "{68F803CCB717F0E5}" {
      FilterPreset "up"
      Sources {
       InputSourceValue "{68F803CCB717F0ED}" {
        Input "keyboard:KC_LSHIFT"
       }
       InputSourceValue "{68F803CCB717F0D2}" {
        Input "keyboard:KC_PRIOR"
        Filter InputFilterRepeat "{68F9110F776125C0}" {
        }
       }
      }
     }
    }
   }
  }
  Action ACE_VerticalZeroingDown {
   Type AnalogRelative
   InputSource InputSourceSum "{68F918F948FDD933}" {
    Sources {
     InputSourceCombo "{68F918F948FDB017}" {
      FilterPreset "down"
      Sources {
       InputSourceValue "{68F918F948FDB014}" {
        Input "keyboard:KC_LSHIFT"
       }
       InputSourceValue "{68F918F948FDB01A}" {
        Input "keyboard:KC_NEXT"
        Filter InputFilterRepeat "{68F918F948FDB01D}" {
        }
       }
      }
     }
    }
   }
  }
  Action ACE_HorizontalZeroingRight {
   Type AnalogRelative
   InputSource InputSourceSum "{68F83C3C13E8E275}" {
    Sources {
     InputSourceCombo "{68F83C3C13E8D2C7}" {
      FilterPreset "right"
      Sources {
       InputSourceValue "{68F83C3C13E8D2CF}" {
        Input "keyboard:KC_LCONTROL"
       }
       InputSourceValue "{68F83C3C13E8D232}" {
        Input "keyboard:KC_PRIOR"
        Filter InputFilterRepeat "{68F83C3C13E8D23B}" {
        }
       }
      }
     }
    }
   }
  }
  Action ACE_HorizontalZeroingLeft {
   Type AnalogRelative
   InputSource InputSourceSum "{68F83C3C037A065C}" {
    Sources {
     InputSourceCombo "{68F83C3C037A064A}" {
      FilterPreset "left"
      Sources {
       InputSourceValue "{68F83C3C037A0648}" {
        Input "keyboard:KC_LCONTROL"
       }
       InputSourceValue "{68F83C3C037A064D}" {
        Input "keyboard:KC_NEXT"
        Filter InputFilterRepeat "{68F83C3C037A05B3}" {
        }
       }
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterWeaponContext {
   ActionRefs +{
    "ACE_VerticalZeroingUp"
    "ACE_VerticalZeroingDown"
    "ACE_HorizontalZeroingRight"
    "ACE_HorizontalZeroingLeft"
   }
  }
  ActionContext CharacterWeaponAimContext {
   ActionRefs +{
    "ACE_VerticalZeroingUp"
    "ACE_VerticalZeroingDown"
    "ACE_HorizontalZeroingRight"
    "ACE_HorizontalZeroingLeft"
   }
  }
 }
}