SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{60C72E6BAD884638}" {
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{68F951238C2255D8}" {
     m_sActionName "separator"
     m_sDisplayName "#ACE_Scopes-AddonName"
    }
    SCR_KeyBindingEntry "{68F9512C565D085E}" {
     m_sActionName "ACE_VerticalZeroingUp"
     m_sDisplayName "#ACE_Scopes-KeyBind_VerticalZeroingUp_Name"
     m_sPreset "up"
    }
    SCR_KeyBindingEntry "{68F95123FFE65133}" {
     m_sActionName "ACE_VerticalZeroingDown"
     m_sDisplayName "#ACE_Scopes-KeyBind_VerticalZeroingDown_Name"
     m_sPreset "down"
    }
    SCR_KeyBindingEntry "{68F95123F70B833E}" {
     m_sActionName "ACE_HorizontalZeroingRight"
     m_sDisplayName "#ACE_Scopes-KeyBind_ACE_HorizontalZeroingRight_Name"
     m_sPreset "right"
    }
    SCR_KeyBindingEntry "{68F95123E2444070}" {
     m_sActionName "ACE_HorizontalZeroingLeft"
     m_sDisplayName "#ACE_Scopes-KeyBind_ACE_HorizontalZeroingLeft_Name"
     m_sPreset "left"
    }
   }
  }
 }
}