ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A656306B3E116E9}" {
   m_sEntityPrefab "{711D022F9BC4B03F}Prefabs/Weapons/Barrels/ACE_Overheating_SpareBarrel.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A656306AA9DCC4E}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
    }
   }
  }
 }
}