ACE_EntityCatalogMultiListEntry : "{0AFC873567388CDE}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Equipment.conf" {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{65270736F5B33C47}" {
   m_sEntityPrefab "{B3F2B47340817ED6}Prefabs/Items/ACE_Facepaint_01_US.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{62F30440549B386D}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}