StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{651955123012A595}" {
   Id "#ACE_Medical-Notification_DefibrillatorShockDelivered"
   Target_en_us "Shock Delivered - Total Shocks This Arrest: %1"
   Modified 1696615833
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D20FF922B}" {
   Id "#ACE_Medical_DefibrillatorAnalyseUserAction_Name"
   Target_en_us "Analyse"
   Modified 1696615836
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D97FE59E2}" {
   Id "#ACE_Medical_DefibrillatorChargeUserAction_Name"
   Target_en_us "Charge"
   ActorGender NONE
   Terminology NONE
   Modified 1696615839
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040FF6C2CEBF}" {
   Id "#ACE_Medical_DefibrillatorConnectPatientUserAction_Name"
   Target_en_us "Connect Patient"
   Modified 1696615844
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040150B7DA8A}" {
   Id "#ACE_Medical_DefibrillatorConnectPatientUserAction_UserName"
   Target_en_us "Connect Patient: %1"
   Modified 1696615847
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D31A8CD27}" {
   Id "#ACE_Medical_DefibrillatorDeliverShockUserAction_Name"
   Target_en_us "Deliver Shock"
   Modified 1696615851
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040E3A1518BC}" {
   Id "#ACE_Medical_DefibrillatorDisconnectUserAction_Name"
   Target_en_us "Disconnect"
   Modified 1696615049
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040E5F66A5A1}" {
   Id "#ACE_Medical_DefibrillatorPickUpUserAction_Name"
   Target_en_us "Pickup & Disconnect"
   Modified 1696478942
   Author "Hypoxic"
   LastChanged "Anthony"
  }
 }
}