StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68440A1FE780317F}" {
   Id "ACE-Medical-Defibrillation-ConnectPatient"
   Target_en_us "Connect Patient"
   Status DEVELOPMENT_DONE
   Modified 1749313707
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{68440A1FB5E26172}" {
   Id "ACE-Medical-Defibrillation-DeliverShock"
   Target_en_us "Deliver Shock"
   Status PROOFREADING_PENDING
   Modified 1749313709
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{68440A1F845D38EF}" {
   Id "ACE-Medical-Defibrillation-DisconnectPatient"
   Target_en_us "Disconnect Patient"
   Modified 1749319273
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{684476910A6F7F1C}" {
   Id "ACE-Medical-Defibrillation-Pickup"
   Target_en_us "Pick Up"
   Status DEVELOPMENT_DONE
   Modified 1749319268
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
 }
}