StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6857508BC1AB85AD}" {
   Id "ACE-MedicalDefibrillation_Notification_PatientConnected"
   Target_en_us "Patient connected"
   Modified 1750561758
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{6857508BCBFAFE72}" {
   Id "ACE-MedicalDefibrillation_Notification_PatientDisconnected"
   Target_en_us "Patient disconnected"
   Modified 1750561769
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{6857508B9214D20B}" {
   Id "ACE-MedicalDefibrillation_Notification_ShockDelivered"
   Target_en_us "Shock delivered"
   Modified 1750561843
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{6857508BE557A595}" {
   Id "ACE-MedicalDefibrillation_Notification_UnableToConnectPatient"
   Target_en_us "Unable to connect patient"
   Modified 1750561820
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{68440A1FE780317F}" {
   Id "ACE-MedicalDefibrillation_UserAction_ConnectPatient"
   Target_en_us "Connect patient"
   Target_de_de "Verbinde Patient"
   Status DEVELOPMENT_PENDING
   Modified 1749719023
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{684A8C40BA16FF1E}" {
   Id "ACE-MedicalDefibrillation_UserAction_DeliverShock"
   Target_en_us "Deliver shock"
   Target_de_de "Schock auslösen"
   Modified 1749719135
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{68440A1F845D38EF}" {
   Id "ACE-MedicalDefibrillation_UserAction_DisconnectPatient"
   Target_en_us "Disconnect patient"
   Target_de_de "Patient trennen"
   Modified 1749719041
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{698F36C018AF65DF}" {
   Id "ACE_MedicalDefibrillation-Defibrillator_DisplayName"
   Target_en_us "ACE Defibrillator"
   Modified 1770993618
   Author "Hypoxic"
   LastChanged "steamuser"
  }
  CustomStringTableItem "{698F36C1F37B0969}" {
   Id "ACE_MedicalDefibrillation_DefibrillatorAED_DisplayName"
   Target_en_us "ACE Automated External Defibrillator"
   Modified 1770995980
   Author "steamuser"
   LastChanged "steamuser"
  }
 }
}