StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{655C16F84C044F7B}" {
   Id "ACE_MedicalDefibrillation-AED_DisplayName"
   Target_en_us "Automated External Defibrillator (AED)"
   Modified 1700545608
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D20FF922B}" {
   Id "ACE_MedicalDefibrillation-AnalyseUserAction_Name"
   Target_en_us "Analyse"
   ActorGender NONE
   Modified 1696996447
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D97FE59E2}" {
   Id "ACE_MedicalDefibrillation-ChargeUserAction_Name"
   Target_en_us "Charge"
   ActorGender 2147483647
   Terminology NONE
   Modified 1696996463
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040FF6C2CEBF}" {
   Id "ACE_MedicalDefibrillation-ConnectPatientUserAction_Name"
   Target_en_us "Defibrillator | Connect Patient"
   Modified 1697056457
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{655C16F824E4D201}" {
   Id "ACE_MedicalDefibrillation-Defibrillator_DisplayName"
   Target_en_us "Manual Defibrillator"
   Modified 1700545687
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040D31A8CD27}" {
   Id "ACE_MedicalDefibrillation-DeliverShockUserAction_Name"
   Target_en_us "Deliver Shock"
   Modified 1696996471
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040E3A1518BC}" {
   Id "ACE_MedicalDefibrillation-DisconnectUserAction_Name"
   Target_en_us "Disconnect"
   Modified 1696996473
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{65270650C2EC361E}" {
   Id "ACE_MedicalDefibrillation-Notification_DefibrillatorAnalysed"
   Target_en_us "Defibrillator | Analysis: 100%"
   Modified 1697056883
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{65270650E430C64F}" {
   Id "ACE_MedicalDefibrillation-Notification_DefibrillatorCharged"
   Target_en_us "Defibrillator | Charge: 100%"
   Modified 1697056839
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{652411C6AD044D73}" {
   Id "ACE_MedicalDefibrillation-Notification_PatientConnected"
   Target_en_us "Defibrillator | Patient Connected: %1"
   Modified 1697001761
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{6526268C6ABAB194}" {
   Id "ACE_MedicalDefibrillation-Notification_PatientConnected_AI"
   Target_en_us "Defibrillator | Patient Connected: %1 | AI"
   Modified 1697001763
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{65270651F0DD45D7}" {
   Id "ACE_MedicalDefibrillation-Notification_PatientDisconnected"
   Target_en_us "Defibrillator | Patient Disconnected"
   Modified 1697056429
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651955123012A595}" {
   Id "ACE_MedicalDefibrillation-Notification_ShockDelivered"
   Target_en_us "Defibrillator | Shock Delivered - Total Shocks This Arrest: %1"
   Modified 1697001766
   Author "Anthony"
   LastChanged "Anthony"
  }
  CustomStringTableItem "{651E040E5F66A5A1}" {
   Id "ACE_MedicalDefibrillation-PickUpUserAction_Name"
   Target_en_us "Pickup & Disconnect"
   Modified 1696996486
   Author "Anthony"
   LastChanged "Anthony"
  }
 }
}