SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{62492BA9716BD6DE}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{62492BA970C14492}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{62492BA970AE4305}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{62492BA97093EA9A}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{62492BA9707E9575}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{62492BA91DF3244E}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{62492BA91DCB5161}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D13C72C299032F}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D218DEDF7EAE1C}" : "{12790B4E7D42F952}Configs/EntityCatalog/US/ACE_InventoryItems_EntityCatalog_Equipment_US.conf" {
  }
 }
}