StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64771576CD0D94CD}" {
   Id "ACE_Captives-Editor_ContextAction_ToggleCaptive_Name"
   Target_en_us "Toggle take prisoner"
   Target_de_de "Gefangen nehmen umschalten"
   Target_zh_cn "切換為俘虜"
   Target_ko_kr "포로 잡기 토글"
   Target_es_es "Alternar tomar prisionero"
   Target_it_it "Alterna prendere prigioniero"
   Modified 1725224838
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{64771573E31EE7FD}" {
   Id "ACE_Captives-Editor_ContextAction_ToggleSurrender_Name"
   Target_en_us "Toggle surrender"
   Target_de_de "Kapitulieren umschalten"
   Target_zh_cn "切換至投降"
   Target_ko_kr "항복 토글"
   Target_es_es "Alternar rendición"
   Target_it_it "Alterna la resa"
   Modified 1725224258
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{647715709F144553}" {
   Id "ACE_Captives-Emotes_Emote_Surrender_Name"
   Target_en_us "Surrender"
   Target_de_de "Kapitulieren"
   Target_zh_cn "投降"
   Target_ko_kr "항복"
   Target_es_es "Rendirse"
   Target_it_it "Resa"
   Modified 1725224856
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{65030ADCC0783838}" {
   Id "ACE_Captives-UserAction_EscortCaptive"
   Target_en_us "Escort prisoner"
   Target_de_de "Gefangener eskortieren"
   Target_zh_cn "押送俘虜"
   Target_ko_kr "포로 호송"
   Target_es_es "Escoltar prisionero"
   Target_it_it "Scorta prigioniero"
   Modified 1725224352
   Author "Kexanone"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{649D4AECDC295B8D}" {
   Id "ACE_Captives-UserAction_ReleasePrisoner"
   Target_en_us "Release prisoner"
   Target_de_de "Gefangener freilassen"
   Target_zh_cn "釋放俘虜"
   Target_ko_kr "포로 놓기"
   Target_es_es "Soltar prisionero"
   Target_it_it "Liberare il prigioniero"
   Modified 1725224367
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{649D4AEC8449241E}" {
   Id "ACE_Captives-UserAction_TakeAsPrisoner"
   Target_en_us "Take as prisoner"
   Target_de_de "Gefangen nehmen"
   Target_zh_cn "拘捕"
   Target_ko_kr "포로로 잡기"
   Target_es_es "Tomar como prisionero"
   Target_it_it "Prendilo come prigioniero"
   Modified 1725495190
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{64B57CB33881E17B}" {
   Id "ACE_Captives-UserAction_UnloadCaptive"
   Target_en_us "Unload prisoner:"
   Target_de_de "Gefangener ausladen:"
   Target_zh_cn "押解俘虜"
   Target_ko_kr "포로 내리기:"
   Target_es_es "Descargar prisionero:"
   Target_it_it "Scarica il prigioniero:"
   Modified 1725495436
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
 }
}
