StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6698E5EF3C06CEBF}" {
   Id "ace-item-facepaint-uk-description"
   Target_en_us "UK manufactured camouflage face cream stick. Either end has a different colour camouflage cream."
   Modified 1721299661
   Author "Admin"
   LastChanged "Admin"
  }
  CustomStringTableItem "{6698E5EF23C64B58}" {
   Id "ace-item-facepaint-uk-name"
   Target_en_us "Camouflage Face Cream"
   Modified 1721299657
   Author "Admin"
   LastChanged "Admin"
  }
  CustomStringTableItem "{6698E5E8B65DE72C}" {
   Id "ace-item-facepaint-us-description"
   Target_en_us "US manufactured camouflage face cream stick. Either end has a different colour camouflage cream."
   Modified 1721298554
   Author "Admin"
   LastChanged "Admin"
  }
  CustomStringTableItem "{6698E5E8B4523D5E}" {
   Id "ace-item-facepaint-us-name"
   Target_en_us "Camouflage Face Cream"
   Modified 1721298508
   Author "Admin"
   LastChanged "Admin"
  }
  CustomStringTableItem "{6698E5E8B00BF20B}" {
   Id "ace-item-facepaint-ussr-description"
   Target_en_us "Soviet manufactured camouflage face cream stick."
   Modified 1721298533
   Author "Admin"
   LastChanged "Admin"
  }
  CustomStringTableItem "{6698E5E8B3B8B6E0}" {
   Id "ace-item-facepaint-ussr-name"
   Target_en_us "Camouflage Face Cream"
   Modified 1721298511
   Author "Admin"
   LastChanged "Admin"
  }
 }
}