StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{667B2E0B01C5BDEC}" {
   Id "ACE_Weather-AddonName"
   Target_en_us "ACE Weather"
   Modified 1719367753
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{667B2E0B3C32F8F7}" {
   Id "ACE_Weather-Keybind_WindInfoToggle"
   Target_en_us "Show wind info"
   Target_fr_fr "Afficher les informations sur le vent"
   Target_it_it "Mostra informazioni sul vento"
   Target_de_de "Zeige Windinformationen"
   Target_es_es "Mostrar información del viento"
   Target_cs_cz "Zobrazit údaje o větru"
   Target_pl_pl "Pokaż inf. o wietrze"
   Target_ru_ru "Показать информацию о ветре"
   Target_ja_jp "風速を表示"
   Target_ko_kr "바람 정보 표시"
   Target_pt_br "Mostrar informação do vento"
   Target_zh_cn "顯示風力資訊"
   Target_uk_ua "Показати інформацію про вітер"
   Modified 1719368269
   Author "Kex"
   LastChanged "Kex"
  }
 }
}