StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB746AAD040EB76}" {
   Id "ACE_Chopping_RemoveBush"
   Target_en_us "Remove Bush"
   Target_fr_fr "Retirer le buisson"
   Target_it_it "Rimuovi cespuglio"
   Target_de_de "Busch entfernen"
   Target_es_es "Remover arbusto"
   Target_cs_cz "Posekat porost"
   Target_ru_ru "Убрать куст"
   Target_ko_kr "수풀 제거"
   Target_pt_br "Remover mato"
   Target_zh_cn "清除樹叢"
   Target_uk_ua "Прибрати кущ"
   Modified 1750690925
   Author "kexanone"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{5EB746AAD5FF74DB}" {
   Id "ACE_Chopping_RemoveTree"
   Target_en_us "Remove Tree"
   Target_fr_fr "Retirer l'arbre"
   Target_it_it "Rimuovi albero"
   Target_de_de "Baum entfernen"
   Target_es_es "Remover árbol"
   Target_cs_cz "Pokácet strom"
   Target_ru_ru "Убрать дерево"
   Target_ko_kr "나무 제거"
   Target_pt_br "Remover árvore"
   Target_zh_cn "砍樹"
   Target_uk_ua "Прибрати дерево"
   Modified 1750690903
   Author "kexanone"
   LastChanged "KingDaddyBoyz"
  }
 }
}