StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB746AAD040EB76}" {
   Id "ACE_Chopping_RemoveBush"
   Target_en_us "Remove Bush"
   Target_fr_fr "Retirer le buisson"
   Target_de_de "Busch entfernen"
   Target_cs_cz "Posekat porost"
   Target_ru_ru "Убрать куст"
   Target_uk_ua "Прибрати кущ"
   Modified 1655483584
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{5EB746AAD5FF74DB}" {
   Id "ACE_Chopping_RemoveTree"
   Target_en_us "Remove Tree"
   Target_fr_fr "Retirer l'arbre"
   Target_de_de "Baum entfernen"
   Target_cs_cz "Pokácet strom"
   Target_ru_ru "Убрать дерево"
   Target_uk_ua "Прибрати дерево"
   Modified 1655483566
   Author "kexanone"
   LastChanged "Smith"
  }
 }
}
