StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5EB746AAD040EB76}" {
   Id "ACE_Chopping_RemoveBush"
   Target_en_us "Remove Bush"
   Target_fr_fr "Retirer le buisson"
   Target_de_de "Busch entfernen"
   Target_cs_cz "Posekat porost"
   Modified 1589072860
   Author "kexanone"
   LastChanged "apollo-jk"
  }
  CustomStringTableItem "{5EB746AAD5FF74DB}" {
   Id "ACE_Chopping_RemoveTree"
   Target_en_us "Remove Tree"
   Target_fr_fr "Retirer l'arbre"
   Target_de_de "Baum entfernen"
   Target_cs_cz "Pokácet strom"
   Modified 1589072745
   Author "kexanone"
   LastChanged "apollo-jk"
  }
 }
}