site:
  name: ACE Anvil
  site: https://anvil.acemod.org
  base: /
  description: ACE3 is a joint effort by the teams behind ACE 2, AGM and CSE to improve the realism and authenticity of Arma 3.
  keywords: Advanced Combat Enhancement 3, ACE, ACE3, Arma, Arma 3, Mod, Modification, Realism, AGM, CSE, Bohemia, Interactive
  themeColor: '#da2c6c'
ace:
  githubUrl: https://github.com/acemod/ACE3
  version:
    major: 0
    minor: 0
    patch: 1
    build: 1337
