StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A6B57640660E5CF}" {
   Id "ACE_Wirecutters-Item_Wirecutters_Description"
   Target_en_us "Tool for cutting wire fences and razor wires."
   Target_de_de "Werkzeug zum Schneiden von Maschendraht und Klingendraht."
   Modified 1785424210
   Author "Kexanone"
   LastChanged "Kex"
  }
  CustomStringTableItem "{6A6B5764041B180B}" {
   Id "ACE_Wirecutters-Item_Wirecutters_Name"
   Target_en_us "Wire Cutters"
   Target_de_de "Seitenschneider"
   Modified 1785420872
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6A6B7283B2E5FA03}" {
   Id "ACE_Wirecutters-UserAction_CutWire_Name"
   Target_en_us "Cut wire"
   Target_de_de "Draht schneiden"
   Modified 1785428940
   Author "Kex"
   LastChanged "Kex"
  }
 }
}