SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68F60CE8757407E8}" {
     m_sEntityPrefab "{03C6EB1EBD25AA33}scripts/Game/ACE_Ballistics/ACE_BallisticTable_US.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68F60CE875732DB6}" {
       m_eItemType SNIPER_RIFLE
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}