SCR_EditorAttributeList {
 m_aAttributes {
  SCR_AIWaypointArtillerySupportAmmoTypeAttribute "{62B0A09621392742}" {
   m_aValues {
    SCR_EditorAttributeFloatStringValueHolder "{69DE1550F67A4140}" {
     m_sEntryName "#ACE_CBRN-AmmunitionType_Poison"
     m_fEntryFloatValue 42
    }
   }
  }
 }
}