SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F14BDB1A7}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F148714C4}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F137C9AFF}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F1351A624}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F13464B23}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F13240031}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D102AC4014161D}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D2108063218CBD}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_InventoryItems_EntityCatalog_Equipment_USSR.conf" {
  }
 }
}