SCR_EntityCatalogMultiList {
 m_aMultiLists {
  ACE_EntityCatalogMultiListEntry "{69D102AC4014161D}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D2108063218CBD}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_InventoryItems_EntityCatalog_Equipment_USSR.conf" {
  }
 }
}