SCR_EntityCatalogMultiList {
 m_aMultiLists {
  ACE_EntityCatalogMultiListEntry "{69D102AC4014161D}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_USSR_InventoryItems.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69CF77A1224A02E0}" {
     m_sEntityPrefab "{B9E98F1464E93A9E}Prefabs/Items/Equipment/Patches/ACE_AnvilPatch_GRS.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69CF77A1250C3B2D}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69D0F455F486EC70}" {
     m_sEntityPrefab "{EDAF32E60741A6F1}Prefabs/Items/Equipment/Patches/ACE_MedicPatch_GRS.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69D0F455F485109F}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}