StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62F97CC0A64ED598}" {
   Id "ACE_TacticalLadder-Item_Description"
   Target_en_us "Portable ladder for scaling obstacles or tactical entry."
   Target_de_de "Tragbare Leiter zum Überwinden von Hindernissen oder für taktisches Eindringen."
   Modified 1660551731
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62F97CC0ADB17508}" {
   Id "ACE_TacticalLadder-Item_Name"
   Target_en_us "Telescopic Ladder"
   Target_fr_fr "Echelle télescopique"
   Target_it_it "Scala Telescopica"
   Target_de_de "Teleskopleiter"
   Target_es_es "Escalera telescópica"
   Target_cs_cz "Teleskopický žebřík"
   Target_pl_pl "Drabina teleskopowa"
   Target_ru_ru "Телескопическая лестница"
   Target_ja_jp "伸縮はしご"
   Target_ko_kr "접이식 사다리"
   Target_pt_br "Escada telescópica"
   Target_zh_cn "伸縮梯子"
   Modified 1660517865
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62F97CC046FFD8B6}" {
   Id "ACE_TacticalLadder-UserAction_Extend"
   Target_en_us "Extend"
   Target_fr_fr "Ajuster"
   Target_it_it "Estendi"
   Target_de_de "Ausfahren"
   Target_es_es "Extender"
   Target_cs_cz "Prodloužit"
   Target_pl_pl "Rozłóż"
   Target_ru_ru "Разложить"
   Target_ja_jp "伸ばす"
   Target_ko_kr "늘리기"
   Target_pt_br "Estender"
   Target_zh_cn "伸長梯子"
   Modified 1660518051
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{650728115F9B1510}" {
   Id "ACE_TacticalLadder-UserAction_TooShort"
   Target_en_us "Too short"
   Target_de_de "Zu kurz"
   Modified 1694973490
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6507280146ED7892}" {
   Id "ACE_TacticalLadder-UserAction_TopExitObstructed"
   Target_en_us "Top exit obstructed"
   Target_de_de "Oberste Sprosse nicht zugänglich"
   Modified 1694981878
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}