StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62F97CC0A64ED598}" {
   Id "ACE_TacticalLadder-Item_Description"
   Target_en_us "Portable ladder for scaling obstacles or tactical entry."
   Target_it_it "Scala portatile per superare ostacoli o accesso tattico."
   Target_de_de "Tragbare Leiter zum Überwinden von Hindernissen oder für taktisches Eindringen."
   Target_es_es "Escalera portátil para escalar obstáculos o entrada táctica."
   Target_zh_cn "便攜式伸縮梯，用於攀爬或戰術突入"
   Target_ko_kr "장애물을 오르거나 전술 진입을 위한 휴대용 사다리입니다."
   Target_pt_br "Escada portátil para escalar obstáculos ou entrada tática."
   Target_zh_cn "便攜式伸縮梯，用於攀爬或戰術突入"
   Modified 1750692357
   Author "Kexanone"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{62F97CC0ADB17508}" {
   Id "ACE_TacticalLadder-Item_Name"
   Target_en_us "Telescopic Ladder"
   Target_fr_fr "Echelle télescopique"
   Target_it_it "Scala Telescopica"
   Target_de_de "Teleskopleiter"
   Target_es_es "Escalera telescópica"
   Target_cs_cz "Teleskopický žebřík"
   Target_pl_pl "Drabina teleskopowa"
   Target_ru_ru "Телескопическая лестница"
   Target_ja_jp "伸縮はしご"
   Target_ko_kr "접이식 사다리"
   Target_pt_br "Escada telescópica"
   Target_zh_cn "伸縮梯"
   Modified 1725492044
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{62F97CC046FFD8B6}" {
   Id "ACE_TacticalLadder-UserAction_Extend"
   Target_en_us "Extend"
   Target_fr_fr "Ajuster"
   Target_it_it "Estendi"
   Target_de_de "Ausfahren"
   Target_es_es "Extender"
   Target_cs_cz "Prodloužit"
   Target_pl_pl "Rozłóż"
   Target_ru_ru "Разложить"
   Target_ja_jp "伸ばす"
   Target_ko_kr "늘리기"
   Target_pt_br "Estender"
   Target_zh_cn "拉伸梯子"
   Modified 1725491968
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{650728115F9B1510}" {
   Id "ACE_TacticalLadder-UserAction_TooShort"
   Target_en_us "Too short"
   Target_it_it "Lunghezza insufficiente"
   Target_de_de "Zu kurz"
   Target_es_es "Muy corto"
   Target_zh_cn "太短"
   Target_ko_kr "너무 짧음"
   Target_pt_br "Muito curto"
   Target_zh_cn "太短"
   Modified 1750692387
   Author "Kexanone"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{6507280146ED7892}" {
   Id "ACE_TacticalLadder-UserAction_TopExitObstructed"
   Target_en_us "Top exit obstructed"
   Target_it_it "Uscita superiore ostruita"
   Target_de_de "Oberste Sprosse nicht zugänglich"
   Target_es_es "Salida superior obstruida"
   Target_zh_cn "梯頂受阻"
   Target_ko_kr "위쪽 출구 막힘"
   Target_pt_br "Saída superior obstruída"
   Target_zh_cn "梯頂受阻"
   Modified 1750692406
   Author "Kexanone"
   LastChanged "KingDaddyBoyz"
  }
 }
}