ACE_EntityCatalogMultiListEntry : "{0AFC873567388CDE}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Equipment.conf" {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69DE154744A3CB83}" {
   m_sEntityPrefab "{AB26FC33B07A6703}Prefabs/Weapons/Ammo/ACE_Ammo_Shell_82mm_ChokingAgent_D832DU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69DE154744A3BE34}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 50
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{69E224A9CD02DCC4}" {
   m_sEntityPrefab "{9244B4DC75D45352}Prefabs/Weapons/Ammo/ACE_Ammo_Shell_82mm_Sarin_D832DU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69E224A9CD02DC6A}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 100
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}