SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_HeldItemAvailableActionContext "{69AD0AE0081B4C05}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0AE07D52BD48}" {
     m_eConsumableType ACE_MEDICAL_EPINEPHRINE_INJECTOR
    }
   }
   m_sTag "APPLY_EPINEPHRINE"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-EpinephrineInjectionAction"
  }
  SCR_HeldItemAvailableActionContext "{69AD0AE474A34D39}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0AE474A34C14}" {
     m_eConsumableType ACE_MEDICAL_METOPROLOL_INJECTOR
    }
   }
   m_sTag "APPLY_METOPROLOL"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-MetoprololInjectionAction"
  }
  SCR_HeldItemAvailableActionContext "{69AD0AE4547FB688}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0AE4547FB6D5}" {
     m_eConsumableType ACE_MEDICAL_AMMONIUM_CARBONATE
    }
   }
   m_sTag "APPLY_AMMONIUM_CARBONATE"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-AmmoniumCarbonatePackageAction"
  }
  SCR_HeldItemAvailableActionContext "{69AD0AE4FEC69D33}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0AE4FEC69C99}" {
     m_eConsumableType ACE_MEDICAL_NALOXONE_INJECTOR
    }
   }
   m_sTag "APPLY_NALOXONE"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-NaloxoneInjectionAction"
  }
  SCR_HeldItemAvailableActionContext "{69AD0AE4E9B34B09}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0AE4E9B34B57}" {
     m_eConsumableType ACE_MEDICAL_PHENYLEPHRINE_INJECTOR
    }
   }
   m_sTag "APPLY_PHENYLEPHRINE"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-PhenylephrineInjectionAction"
  }
 }
}