ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69B604869DAB86EF}" {
   m_sEntityPrefab "{3DD5351CFB98FC7F}Prefabs/Items/Equipment/MineDetector/ACE_MineDetector_VMM3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69B419EA8D15FDCE}" {
     m_eItemType EQUIPMENT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{69BB0467BF932218}" {
   m_sEntityPrefab "{619F4A05EE0F4105}Prefabs/Items/Equipment/Detonators/ACE_DeadManSwitch.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69BB0467BF9325F5}" {
     m_eItemType EXPLOSIVES
     m_iSupplyCost 15
    }
   }
  }
 }
}