ACE_EntityCatalogMultiListEntry : "{0AFC873567388CDE}Configs/EntityCatalog/ACE_InventoryItemsBase.conf" {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{68EB10F5497121E7}" {
   m_sEntityPrefab "{1642314A5C9B5C13}Prefabs/Items/ACE_Facepaint_01_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{62F30440549B386D}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}