SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   Rules {
    ComponentClassGarbageRule "{6A0D47C05C245426}" {
     Filter "ACE_Medical_LitterComponent"
     Lifetime 600
     CheckPlayerDistance 0
    }
   }
  }
  ACE_Medical_SecondChanceSystem "{658D0E49B8A49251}" {
  }
 }
}