@startuml
partition "Advanced Medical - First Aid" {
  start

  if (Is bleeding?) then (yes)
    :Bandage/Tourniquet\nwounds;
  else (no)
  endif

  if (Is unconscious?) then (no)
    stop
  else (yes)
  endif

  if (Airways obstructed?) then (yes)
    :Open airways;
  else (no)
  endif

  if (Is breathing?) then (no)
    :Commence CPR\nuntil medic arrives;
    stop
  else (yes)
  endif

  :Put in recovery\nposition;

  if (Lost blood?) then (yes)
    :Administer saline;
  else (no)
  endif

  if (Is in pain?) then (yes)
    :Inject morhpine;
  else (no)
  endif

  if (Is awake?) then (yes)
    end
  else (no)
  endif

  if (Too injured for\nepinephrine?) then (yes)
    :Heal wounds with\nmedical kit;
  else (no)
  endif

  :Inject epinephrine;
  end
}
@enduml