SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65270736038395D9}" {
     m_sEntityPrefab "{28FA34E692783ACB}Prefabs/Items/ACE_Facepaint_01_USSR.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{62F30440549B386D}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}
