StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{69E1591BB97861B9}" {
   Id "ACE_CBRN-AtropineOximeInjectionAction"
   Target_en_us "Inject atropine/oxime"
   Target_de_de "Atropin/Oxime injizieren"
   Modified 1776376743
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E41A49A04582D5}" {
   Id "ACE_CBRN-EditableEntity_DamageArea_ChokingAgent"
   Target_en_us "Choking Agent Contaminated Area"
   Target_de_de "Lungenkampfstoff Kontaminiertes Gebiet"
   Modified 1776557283
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E41A49ACF6A801}" {
   Id "ACE_CBRN-EditableEntity_DamageArea_Sarin"
   Target_en_us "Sarin Nerve Agent Contaminated Area"
   Target_de_de "Sarin Nervenkampfstoff Kontaminiertes Gebiet"
   Modified 1776557523
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE154D8B1BAEFD}" {
   Id "ACE_CBRN-EditableEntity_EffectModule_Mortar_ChokingAgent"
   Target_en_us "Choking Agent Mortar Shell"
   Target_de_de "Lungenkampfstoff Mörsergeschoss"
   Modified 1776384940
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E224AC57B2E30B}" {
   Id "ACE_CBRN-EditableEntity_EffectModule_Mortar_Sarin"
   Target_en_us "Sarin Nerve Agent Mortar Shell"
   Target_de_de "Sarin Nervenkampfstoff Mörsergeschoss"
   Modified 1776430389
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E2EEFA4186B2F8}" {
   Id "ACE_CBRN-FailReason_Paralyzed"
   Target_en_us "Paralyzed"
   Target_de_de "Gelähmt"
   Modified 1776490983
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69D73111C5F0A103}" {
   Id "ACE_CBRN-Headgear_GasMask_Description"
   Target_en_us "Mask for eye and respiratory protection."
   Target_de_de "Maske zum Schutz von Augen und Atemwege."
   Modified 1775711398
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69D73111FD9B5514}" {
   Id "ACE_CBRN-Headgear_GasMask_M50_Name"
   Target_en_us "M50 Protective Mask"
   Target_de_de "M50 Atemschutzmaske"
   Modified 1775711272
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E1591AF97FE150}" {
   Id "ACE_CBRN-InfoWidget_Atropine"
   Target_en_us "Atropine inhibits acetylcholine "
   Target_de_de "Atropin hemmt Acetylcholin"
   Modified 1776378532
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1550112E09A5}" {
   Id "ACE_CBRN-InfoWidget_ChemicalWeaponBan"
   Target_en_us "Outlawed by Geneva Protocol and Chemical Weapon Convention"
   Target_de_de "Verboten durch Genfer Protokol und Chemiewaffenkonvention"
   Modified 1776384843
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E161C4CE31817F}" {
   Id "ACE_CBRN-InfoWidget_Oxime"
   Target_en_us "Oxime reactivates acetylcholinesterase"
   Target_de_de "Oxim reaktiviert Acetylcholinesterase"
   Modified 1776378542
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E1591B2CA49E10}" {
   Id "ACE_CBRN-Item_AtropineOxime_Description"
   Target_en_us "Administered to patients paralyzed by nerve agents."
   Target_de_de "Verabreicht an Patienten mit Vergiftung durch Nervenkampfstoffe."
   Modified 1776486936
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E1591B2B7C64C9}" {
   Id "ACE_CBRN-Item_AtropineOxime_Name"
   Target_en_us "Atropine/Oxime"
   Target_de_de "Atropin/Oxim"
   Modified 1776376740
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1546254C75F8}" {
   Id "ACE_CBRN-Magazine_D832DU_ChokingAgent_Description"
   Target_en_us "Phosgene–chlorine mixture shell for Soviet 82mm mortars."
   Target_de_de "Phosgen-Chlor Gemisch für sowjetische 82mm-Mörser."
   Modified 1776385070
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE15462032AD08}" {
   Id "ACE_CBRN-Magazine_D832DU_ChokingAgent_Name"
   Target_en_us "82mm D-832DU Choking Agent Shell"
   Target_de_de "82mm D-832DU Lungenkampfstoff Geschoss"
   Modified 1776385049
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E224AE7722B9F4}" {
   Id "ACE_CBRN-Magazine_D832DU_NerveAgent_Name"
   Target_en_us "82mm D-832DU Nerve Agent Shell"
   Target_de_de "82mm D-832DU Nervenkapfstoff Geschoss"
   Modified 1776430035
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E224A99DB28870}" {
   Id "ACE_CBRN-Magazine_D832DU_Sarin_Description"
   Target_en_us "Sarin shell for Soviet 82mm mortars."
   Target_de_de "Sarin für sowjetische 82mm-Mörser."
   Modified 1776430082
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1544E6AF83E1}" {
   Id "ACE_CBRN-Magazine_M819_ChokingAgent_Description"
   Target_en_us "Phosgene–chlorine mixture shell for US 81mm mortars."
   Target_de_de "Phosgen-Chlor Mix für US-amerikanische 81mm-Mörser."
   Modified 1776385056
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1544E5BD8DAD}" {
   Id "ACE_CBRN-Magazine_M819_ChokingAgent_Name"
   Target_en_us "81mm M819 Choking Agent Shell"
   Target_de_de "82mm M819 Lungenkampfstoff Geschoss"
   Modified 1776385062
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E224AF46F09DDC}" {
   Id "ACE_CBRN-Magazine_M819_NerveAgent_Name"
   Target_en_us "81mm M819 Nerve Agent Shell"
   Target_de_de "82mm M819 Nervenkampfstoff Geschoss"
   Modified 1776429981
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69E224AF58E886BF}" {
   Id "ACE_CBRN-Magazine_M819_Sarin_Description"
   Target_en_us "Sarin nerve agent shell for US 81mm mortars."
   Target_de_de "Sarin für US-amerikanische 81mm-Mörser."
   Modified 1776429987
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}