StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{69D73111C5F0A103}" {
   Id "ACE_CBRN-Headgear_GasMask_Description"
   Target_en_us "Mask for eye and respiratory protection."
   Target_de_de "Maske zum Schutz von Augen und Atemwege."
   Modified 1775711398
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69D73111FD9B5514}" {
   Id "ACE_CBRN-Headgear_GasMask_M50_Name"
   Target_en_us "M50 Protective Mask"
   Target_de_de "M50 Atemschutzmaske"
   Modified 1775711272
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}