StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{69DE154D8B1BAEFD}" {
   Id "ACE_CBRN-EditableEntity_EffectModule_Mortar_PulTox"
   Target_en_us "Pulmonary Toxin Mortar Shell"
   Target_de_de "Pneumotoxisches Mörsergeschoss"
   Modified 1776166582
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69D73111C5F0A103}" {
   Id "ACE_CBRN-Headgear_GasMask_Description"
   Target_en_us "Mask for eye and respiratory protection."
   Target_de_de "Maske zum Schutz von Augen und Atemwege."
   Modified 1775711398
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69D73111FD9B5514}" {
   Id "ACE_CBRN-Headgear_GasMask_M50_Name"
   Target_en_us "M50 Protective Mask"
   Target_de_de "M50 Atemschutzmaske"
   Modified 1775711272
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1546254C75F8}" {
   Id "ACE_CBRN-Magazine_D832DU_PulmonaryToxin_Description"
   Target_en_us "Phosgene–chlorine mixture shell for Soviet 82mm mortars."
   Target_de_de "Phosgen-Chlor Gemisch für sowjetische 82mm-Mörser."
   Modified 1776163566
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE15462032AD08}" {
   Id "ACE_CBRN-Magazine_D832DU_PulmonaryToxin_Name"
   Target_en_us "82mm D-832DU Pulmonary Toxin Shell"
   Target_de_de "82mm D-832DU Pneumotoxisches Geschoss"
   Modified 1776163502
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1544E6AF83E1}" {
   Id "ACE_CBRN-Magazine_M819_PulmonaryToxin_Description"
   Target_en_us "Phosgene–chlorine mixture shell for US 81mm mortars."
   Target_de_de "Phosgen-Chlor Mix für US-amerikanische 81mm-Mörser."
   Modified 1776163216
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69DE1544E5BD8DAD}" {
   Id "ACE_CBRN-Magazine_M819_PulmonaryToxin_Name"
   Target_en_us "81mm M819 Pulmonary Toxin Shell"
   Target_de_de "82mm M819 Pneumotoxisches Geschoss"
   Modified 1776163600
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}