StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60CF45A3ED3C6951}" {
   Id "ACE_Medical-EpinephrineInjectionAction"
   Target_en_us "Inject epinephrine"
   Target_fr_fr "Injecter de l'adrénaline"
   Target_de_de "Epinephrin injizieren"
   Modified 1627601772
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60C8CE8D36767C39}" {
   Id "ACE_Medical-FailReason_NoPain"
   Target_en_us "Not in pain"
   Target_fr_fr "Ne ressent pas de douleur"
   Target_de_de "Kein Schmerz"
   Modified 1627601757
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60CF45A099EA2D99}" {
   Id "ACE_Medical-FailReason_NotUnconscious"
   Target_en_us "Not unconscious"
   Target_fr_fr "Pas inconscient"
   Target_de_de "Nicht bewusstlos"
   Modified 1627601747
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60F61507D00761D0}" {
   Id "ACE_Medical-FailReason_TooInjured"
   Target_en_us "Too injured"
   Target_fr_fr "Trop grièvement blessé"
   Target_de_de "Zu verletzt"
   Modified 1627601732
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60CF45A17B6601E3}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases wake-up chance"
   Target_fr_fr "Augmente les chances de reprise de connaissance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Modified 1627601717
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60C8F66C4889FFD9}" {
   Id "ACE_Medical-InfoWidget_Morphine"
   Target_en_us "Alleviates severe pain"
   Target_fr_fr "Allège une douleur violente"
   Target_de_de "Lindert starke Schmerzen"
   Modified 1627601705
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60CF45A0A9B86435}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to unconscious patients."
   Target_fr_fr "Administrée à des patients inconscients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Modified 1627601678
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{60CF45A0B47E9549}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_fr_fr "Adrénaline"
   Target_de_de "Epinephrin"
   Modified 1627601655
   Author "kexanone"
   LastChanged "Cheitan"
  }
  CustomStringTableItem "{5E101C5589E004EE}" {
   Id "ACE_Medical-Item_Morphine_Description"
   Target_en_us "Administered to patients in severe pain."
   Target_fr_fr "Administrée à des patients ressentant une douleur violente."
   Target_de_de "Verabreicht an Patienten mit akuten Schmerzen."
   Modified 1627601627
   Author "kexanone"
   LastChanged "Cheitan"
  }
 }
}