StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60CF45A3ED3C6951}" {
   Id "ACE_Medical-EpinephrineInjectionAction"
   Target_en_us "Inject epinephrine"
   Target_de_de "Epinephrin injizieren"
   Modified 1624203691
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60CF45A099EA2D99}" {
   Id "ACE_Medical-FailReason_NotUnconscious"
   Target_en_us "Not unconscious"
   Target_de_de "Nicht bewusstlos"
   Modified 1624202974
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60CF45A17B6601E3}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases wake-up chance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Modified 1624203522
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60CF45A0A9B86435}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to unconscious patients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Modified 1624203609
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60CF45A0B47E9549}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_de_de "Epinephrin"
   Modified 1624202844
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}