StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60C8CE8D36767C39}" {
   Id "ACE_Medical-FailReason_NoPain"
   Target_en_us "Not in pain"
   Target_de_de "Kein Schmerz"
   Modified 1623778230
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60C8F66C4889FFD9}" {
   Id "ACE_Medical-InfoWidget_Morphine"
   Target_en_us "Alleviates severe pain"
   Target_de_de "Lindert starke Schmerzen"
   Modified 1623786532
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5E101C5589E004EE}" {
   Id "ACE_Medical-Item_Morphine_Description"
   Target_en_us "Administered to patients in severe pain."
   Target_de_de "Verabreicht an Patienten mit akuten Schmerzen."
   Modified 1623770742
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}