SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_AvailableActionContext "{6497637586111E0C}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{649774A65B05E6FA}" {
     m_eConsumableType ACE_FACEPAINT
    }
    SCR_IsCharacterConsciousCondition "{649774A4D794E9C7}" {
    }
    ACE_CharacterAppliedFacepaintCondition "{64B91E0658193E58}" {
     m_bNegateCondition 1
    }
   }
   m_sTag "ACE_Apply_Facepaint"
   m_sAction "GadgetActivate"
   m_sName "Apply Face Paint"
  }
  SCR_AvailableActionContext "{64B91548FBED4D7F}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{649774A65B05E6FA}" {
     m_eConsumableType ACE_FACEPAINT
    }
    SCR_IsCharacterConsciousCondition "{649774A4D794E9C7}" {
    }
    ACE_CharacterAppliedFacepaintCondition "{64B91E063668F735}" {
    }
   }
   m_sTag "ACE_Remove_Facepaint"
   m_sAction "GadgetActivate"
   m_sName "Remove Face Paint"
  }
 }
}
