#ifdef ENABLE_DIAG
//------------------------------------------------------------------------------------------------
modded enum SCR_DebugMenuID
{
	ACE_OVERHEATING_DEBUGUI_MENU,
	ACE_OVERHEATING_DEBUGUI_MENU_TEMPERATURE_DIAG,
	ACE_OVERHEATING_DEBUGUI_MENU_JAM_SETTER,
	ACE_OVERHEATING_DEBUGUI_MENU_BARREL_TEMPERATURE_SETTER,
	ACE_OVERHEATING_DEBUGUI_MENU_AMMO_TEMPERATURE_SETTER,
}
#endif