/*!
Notification IDs used by SCR_NotificationsComponent.
*/
modded enum ENotification
{
	ACE_MEDICALDEFIBRILLATION_ANALYSED,
	ACE_MEDICALDEFIBRILLATION_CHARGED,
	ACE_MEDICALDEFIBRILLATION_PATIENTCONNECTED,
	ACE_MEDICALDEFIBRILLATION_PATIENTCONNECTED_AI,
	ACE_MEDICALDEFIBRILLATION_PATIENTDISCONNECTED,
	ACE_MEDICALDEFIBRILLATION_SHOCKDELIVERED
}
