StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60C72E6B3650DD86}" {
   Id "ACE-Acronym"
   Target_en_us "ACE"
   Target_fr_fr "ACE"
   Target_it_it "ACE"
   Target_de_de "ACE"
   Target_es_es "ACE"
   Target_cs_cz "ACE"
   Target_pl_pl "ACE"
   Target_ru_ru "ACE"
   Target_ja_jp "ACE"
   Target_ko_kr "ACE"
   Target_pt_br "ACE"
   Target_zh_cn "ACE"
   Target_uk_ua "ACE"
   Modified 1623668589
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60FD565E5C4D775C}" {
   Id "ACE-Item_Banana_Description"
   Target_en_us "Healthy potassium!"
   Target_de_de "Gesundes Kalium!"
   Modified 1627220515
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60FD565E59AC0571}" {
   Id "ACE-Item_Banana_Name"
   Target_en_us "Banana"
   Target_de_de "Banane"
   Modified 1627220217
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60FD565E50C080B7}" {
   Id "ACE-Weapon_FragBanana_Description"
   Target_en_us "Explosive Potassium!"
   Target_de_de "Explosives Kalium!"
   Modified 1627220356
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{60FD565E48F06F03}" {
   Id "ACE-Weapon_FragBanana_Name"
   Target_en_us "Frag Banana"
   Target_de_de "Granat-Banane"
   Modified 1627220475
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}