StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60C72E6B3650DD86}" {
   Id "ACE-Acronym"
   Target_en_us "ACE"
   Target_fr_fr "ACE"
   Target_it_it "ACE"
   Target_de_de "ACE"
   Target_es_es "ACE"
   Target_cs_cz "ACE"
   Target_pl_pl "ACE"
   Target_ru_ru "ACE"
   Target_ja_jp "ACE"
   Target_ko_kr "ACE"
   Target_pt_br "ACE"
   Target_zh_cn "ACE"
   Target_uk_ua "ACE"
   Modified 1623668589
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{64771570B1AFAB10}" {
   Id "ACE-Emotes_Emote_Pushups_Name"
   Target_en_us "Push-ups"
   Target_de_de "Liegestützen"
   Modified 1685539176
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{64771570304E885F}" {
   Id "ACE-Emotes_Emote_Salute_Name"
   Target_en_us "Salute"
   Target_de_de "Salutieren"
   Modified 1685538873
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{64771570B4AF7606}" {
   Id "ACE-Emotes_Emote_SitOnFloor_Name"
   Target_en_us "Sit on the floor"
   Target_de_de "Auf den Boden sitzen"
   Modified 1685538829
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{60FD565E5C4D775C}" {
   Id "ACE-Item_Banana_Description"
   Target_en_us "Healthy potassium!"
   Target_fr_fr "Potassium bon pour la santé !"
   Target_de_de "Gesundes Kalium!"
   Target_cs_cz "Zdravá dávka draslíku!"
   Target_ru_ru "Здоровый калий!"
   Target_uk_ua "Здоровий калій!"
   Modified 1655483874
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{60FD565E59AC0571}" {
   Id "ACE-Item_Banana_Name"
   Target_en_us "Banana"
   Target_fr_fr "Banane"
   Target_de_de "Banane"
   Target_cs_cz "Banán"
   Target_ru_ru "Банан"
   Target_uk_ua "Банан"
   Modified 1655483813
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{5DDEFB51C773DDD9}" {
   Id "ACE-UserAction_Carry"
   Target_en_us "Carry"
   Target_fr_fr "Porter"
   Target_it_it "Trasporta"
   Target_de_de "Tragen"
   Target_es_es "Portar"
   Target_cs_cz "Nést"
   Target_pl_pl "Nieś"
   Target_ru_ru "Перенести"
   Target_ja_jp "運ぶ"
   Target_ko_kr "업기"
   Target_pt_br "Carregar"
   Target_zh_cn "背起"
   Target_uk_ua "Перенести"
   Modified 1689077928
   Author "kexanone"
   LastChanged "Kex"
  }
  CustomStringTableItem "{5E0C2A71118B03B7}" {
   Id "ACE-UserAction_Carrying"
   Target_en_us "Carrying"
   Target_fr_fr "Porter"
   Target_de_de "Am Tragen"
   Target_cs_cz "Nošení"
   Target_ru_ru "Перенос"
   Target_uk_ua "Перенесення"
   Modified 1655483287
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{64AD6AAED7334824}" {
   Id "ACE-UserAction_LoadCarried"
   Target_en_us "Load carried:"
   Target_de_de "Getragener laden:"
   Modified 1689127000
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{649D4AEF943234F2}" {
   Id "ACE-UserAction_Release"
   Target_en_us "Release"
   Target_fr_fr "Déposer"
   Target_it_it "Lascia"
   Target_de_de "Ablegen"
   Target_es_es "Soltar"
   Target_cs_cz "Položit"
   Target_pl_pl "Puść"
   Target_ru_ru "Отпустить"
   Target_ja_jp "離す"
   Target_ko_kr "놓기"
   Target_pt_br "Soltar"
   Target_zh_cn "放開"
   Target_uk_ua "Відпустити"
   Modified 1689078128
   Author "kexanone"
   LastChanged "Kex"
  }
  CustomStringTableItem "{60FD565E50C080B7}" {
   Id "ACE-Weapon_FragBanana_Description"
   Target_en_us "Explosive Potassium!"
   Target_fr_fr "Potassium explosif !"
   Target_de_de "Explosives Kalium!"
   Target_cs_cz "Výbušná dávka draslíku!"
   Target_ru_ru "Взрывной калий!"
   Target_uk_ua "Вибуховий калій!"
   Modified 1655483802
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{60FD565E48F06F03}" {
   Id "ACE-Weapon_FragBanana_Name"
   Target_en_us "Frag Banana"
   Target_fr_fr "Banane à fragmentation"
   Target_de_de "Granat-Banane"
   Target_cs_cz "Výbušný banán"
   Target_ru_ru "Осколочный банан"
   Target_uk_ua "Осколковий банан"
   Modified 1655483765
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{649D4AEE400FD73C}" {
   Id "ACE_Core-AddonName"
   Target_en_us "Core"
   Modified 1688030694
   Author "Kex"
   LastChanged "Kex"
  }
 }
}