StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60C72E6B3650DD86}" {
   Id "ACE-Acronym"
   Target_en_us "ACE"
   Target_fr_fr "ACE"
   Target_it_it "ACE"
   Target_de_de "ACE"
   Target_es_es "ACE"
   Target_cs_cz "ACE"
   Target_pl_pl "ACE"
   Target_ru_ru "ACE"
   Target_ja_jp "ACE"
   Target_ko_kr "ACE"
   Target_pt_br "ACE"
   Target_zh_cn "ACE"
   Target_uk_ua "ACE"
   Modified 1623668589
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}