ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69E41A3F7031BC0D}" {
   m_sEntityPrefab "{F58403F31A12E76B}Prefabs/Items/Medicine/AtropineOxime/ACE_Medical_AtropineOximeInjection.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69E41A3F7031BBF0}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 3
    }
   }
  }
 }
}