ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  ACE_OptionalEntityCatalogInventoryItem "{69D7256204777D1C}" {
   m_sEntityPrefab "{D5AB630CD1C569B1}Prefabs/Characters/GasMask/GasMask_M50/ACE_GasMask_M50_Headgear.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69D7256239850E32}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 2
    }
   }
   m_sDisallowedAddonGUID "5D0551624969C92E"
  }
  ACE_OptionalEntityCatalogInventoryItem "{69D725624DFB175E}" {
   m_sEntityPrefab "{75F8DC635BA69A3F}Prefabs/Characters/GasMask/GasMask_M50/ACE_GasMask_M50_FaceClothing.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69D725624DFA49D4}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 2
    }
   }
   m_sRequiredAddonGUID "5D0551624969C92E"
  }
 }
}