StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65515E0D98453E42}" {
   Id "ACE_Medical-AddonName"
   Target_en_us "Medical"
   Target_ko_kr "의료"
   Modified 1699833891
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{660F338D19E8B527}" {
   Id "ACE_Medical-Editor_TooltipDetail_Resilience_Name"
   Target_en_us "Resilience"
   Target_de_de "Resilienz"
   Target_ru_ru "Устойчивость"
   Target_zh_cn "恢復力"
   Target_ko_kr "회복력"
   Modified 1725220405
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A3ED3C6951}" {
   Id "ACE_Medical-EpinephrineInjectionAction"
   Target_en_us "Inject epinephrine"
   Target_fr_fr "Injecter de l'adrénaline"
   Target_de_de "Epinephrin injizieren"
   Target_cs_cz "Aplikovat epinefrin"
   Target_ru_ru "Вколоть адреналин"
   Target_uk_ua "Вколоти адреналін"
   Target_zh_cn "注射腎上腺素"
   Target_ko_kr "에피네프린 주사"
   Modified 1725220431
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60C8CE8D36767C39}" {
   Id "ACE_Medical-FailReason_NoPain"
   Target_en_us "Not in pain"
   Target_fr_fr "Ne ressent pas de douleur"
   Target_de_de "Kein Schmerz"
   Target_cs_cz "Bez bolestí"
   Target_ru_ru "Не чувствует боли"
   Target_uk_ua "Не відчуває болю"
   Target_zh_cn "無疼痛"
   Target_ko_kr "통증 없음"
   Modified 1725496849
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A099EA2D99}" {
   Id "ACE_Medical-FailReason_NotUnconscious"
   Target_en_us "Not unconscious"
   Target_fr_fr "Pas inconscient"
   Target_de_de "Nicht bewusstlos"
   Target_cs_cz "Při vědomí"
   Target_ru_ru "В сознании"
   Target_uk_ua "У свідомості"
   Target_zh_cn "未昏迷"
   Target_ko_kr "의식불명이 아님"
   Modified 1725220523
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60F61507D00761D0}" {
   Id "ACE_Medical-FailReason_TooInjured"
   Target_en_us "Too injured"
   Target_fr_fr "Trop grièvement blessé"
   Target_de_de "Zu verletzt"
   Target_cs_cz "Příliš zraněný"
   Target_ru_ru "Слишком раненый"
   Target_uk_ua "Надто поранений"
   Target_zh_cn "傷勢過重"
   Target_ko_kr "부상이 심함"
   Modified 1725497083
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A17B6601E3}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases wake-up chance"
   Target_fr_fr "Augmente les chances de reprise de connaissance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_cs_cz "Zvyšuje pravděpodobnost probuzení se z bezvědomí"
   Target_ru_ru "Увеличивает вероятность пробуждения"
   Target_uk_ua "Збільшує ймовірність пробудження"
   Target_zh_cn "增加甦醒機率"
   Target_ko_kr "의식을 되찾을 확률 증가"
   Modified 1725220754
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60C8F66C4889FFD9}" {
   Id "ACE_Medical-InfoWidget_Morphine"
   Target_en_us "Alleviates severe pain"
   Target_fr_fr "Allège une douleur violente"
   Target_de_de "Lindert starke Schmerzen"
   Target_cs_cz "Zmírňuje silné bolesti"
   Target_ru_ru "Снимает сильную боль"
   Target_uk_ua "Знімає сильний біль"
   Target_zh_cn "緩解劇烈疼痛"
   Target_ko_kr "극심한 통증 완화"
   Modified 1725220793
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A0A9B86435}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to unconscious patients."
   Target_fr_fr "Administrée à des patients inconscients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_cs_cz "Aplikováno pacientům v bezvědomí."
   Target_ru_ru "Назначают пациентам без сознания."
   Target_uk_ua "Призначають пацієнтам без свідомості."
   Target_zh_cn "給予昏迷的患者使用"
   Target_ko_kr "의식불명의 환자에게 투여합니다."
   Modified 1725223370
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A0B47E9549}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_fr_fr "Adrénaline"
   Target_de_de "Epinephrin"
   Target_cs_cz "Epinefrin"
   Target_ru_ru "Инъекция адреналина"
   Target_uk_ua "Ін'єкція адреналіну"
   Target_zh_cn "腎上腺素"
   Target_ko_kr "에피네프린"
   Modified 1725220837
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{5E101C5589E004EE}" {
   Id "ACE_Medical-Item_Morphine_Description"
   Target_en_us "Administered to patients in severe pain."
   Target_fr_fr "Administrée à des patients ressentant une douleur violente."
   Target_de_de "Verabreicht an Patienten mit akuten Schmerzen."
   Target_cs_cz "Aplikováno pacientům v silných bolestech."
   Target_ru_ru "Назначают пациентам с сильной болью."
   Target_uk_ua "Призначають пацієнтам із сильним болем."
   Target_zh_cn "用於治療劇烈疼痛的患者"
   Target_ko_kr "극심한 통증을 호소하는 환자에게 투여합니다."
   Modified 1725222289
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65515E08A4E02C61}" {
   Id "ACE_Medical-KeyBind_OpenRadialMenu"
   Target_en_us "Open medical radial menu"
   Target_de_de "Öffne medizinisches Kreismenü"
   Target_ru_ru "Открыть меню медицины"
   Target_zh_cn "打開醫療環形選單"
   Target_ko_kr "원형 의료 메뉴 열기"
   Modified 1725496962
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A9625D01268}" {
   Id "ACE_Medical-RadialMenu_ExaminePatient"
   Target_en_us "Examine patient"
   Target_de_de "Patient untersuchen"
   Target_ru_ru "Осмотреть пациента"
   Target_zh_cn "檢查傷患"
   Target_ko_kr "환자 검사"
   Modified 1725496555
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A94855EB699}" {
   Id "ACE_Medical-RadialMenu_FluidReplacement"
   Target_en_us "Fluid Replacement"
   Target_de_de "Volumentherapie"
   Target_ru_ru "Восполнение объёма крови"
   Target_zh_cn "補液"
   Target_ko_kr "체액 복구"
   Modified 1725221453
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A967A9EA7B6}" {
   Id "ACE_Medical-RadialMenu_FractureManagement"
   Target_en_us "Fracture management"
   Target_de_de "Frakturbehandlung"
   Target_ru_ru "Лечение перелома"
   Target_zh_cn "骨折處置"
   Target_ko_kr "골절 관리"
   Modified 1725497003
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A94A58D1608}" {
   Id "ACE_Medical-RadialMenu_HemorrhageControl"
   Target_en_us "Hemorrhage control"
   Target_de_de "Blutstillung"
   Target_ru_ru "Контроль кровоизлияния"
   Target_zh_cn "止血"
   Target_ko_kr "지혈"
   Modified 1725221536
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A97B16C0831}" {
   Id "ACE_Medical-RadialMenu_Medication"
   Target_en_us "Medication"
   Target_de_de "Medikation"
   Target_ru_ru "Медикаменты"
   Target_zh_cn "藥物治療"
   Target_ko_kr "약물"
   Modified 1725221632
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{630D4CCE326184CA}" {
   Id "ACE_Medical-UserAction_BackPosition"
   Target_en_us "Put on back"
   Target_de_de "Auf den Rücken drehen"
   Target_ru_ru "Положить на спину"
   Target_zh_cn "協助仰躺"
   Target_ko_kr "똑바로 눕히기"
   Modified 1725496394
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{630D4CCE36458E06}" {
   Id "ACE_Medical-UserAction_LeftRecoveryPosition"
   Target_en_us "Put in left recovery position"
   Target_de_de "In linke Bewusstlosenlagerung bringen"
   Target_ru_ru "Положить на левый бок"
   Target_zh_cn "轉為左側復甦姿勢"
   Target_ko_kr "좌측으로 회복자세 교정하기"
   Modified 1725496514
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64FB538E9326BF80}" {
   Id "ACE_Medical-UserAction_RightRecoveryPosition"
   Target_en_us "Put in right recovery position"
   Target_de_de "In rechte Bewusstlosenlagerung bringen"
   Target_ru_ru "Положить на правый бок"
   Target_zh_cn "轉為右側復甦姿勢"
   Target_ko_kr "우측으로 회복자세 교정하기"
   Modified 1725496522
   Author "Kexanone"
   LastChanged "Psycool"
  }
 }
}
