StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65515E0D98453E42}" {
   Id "ACE_Medical-AddonName"
   Target_en_us "Medical"
   Target_ko_kr "의료"
   Modified 1699833891
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{660F338D19E8B527}" {
   Id "ACE_Medical-Editor_TooltipDetail_Resilience_Name"
   Target_en_us "Resilience"
   Target_de_de "Resilienz"
   Target_ko_kr "회복력"
   Modified 1712273696
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A3ED3C6951}" {
   Id "ACE_Medical-EpinephrineInjectionAction"
   Target_en_us "Inject epinephrine"
   Target_fr_fr "Injecter de l'adrénaline"
   Target_de_de "Epinephrin injizieren"
   Target_cs_cz "Aplikovat epinefrin"
   Target_ru_ru "Вколоть адреналин"
   Target_uk_ua "Вколоти адреналін"
   Target_ko_kr "에피네프린 주사하기"
   Modified 1655484699
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60C8CE8D36767C39}" {
   Id "ACE_Medical-FailReason_NoPain"
   Target_en_us "Not in pain"
   Target_fr_fr "Ne ressent pas de douleur"
   Target_de_de "Kein Schmerz"
   Target_cs_cz "Bez bolestí"
   Target_ru_ru "Не чувствует боли"
   Target_uk_ua "Не відчуває болю"
   Target_ko_kr "통증 없음"
   Modified 1655484680
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A099EA2D99}" {
   Id "ACE_Medical-FailReason_NotUnconscious"
   Target_en_us "Not unconscious"
   Target_fr_fr "Pas inconscient"
   Target_de_de "Nicht bewusstlos"
   Target_cs_cz "Při vědomí"
   Target_ru_ru "В сознании"
   Target_uk_ua "У свідомості"
   Target_ko_kr "의식불명이 아님"
   Modified 1655484622
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60F61507D00761D0}" {
   Id "ACE_Medical-FailReason_TooInjured"
   Target_en_us "Too injured"
   Target_fr_fr "Trop grièvement blessé"
   Target_de_de "Zu verletzt"
   Target_cs_cz "Příliš zraněný"
   Target_ru_ru "Слишком раненый"
   Target_uk_ua "Надто поранений"
   Target_ko_kr "부상이 심함"
   Modified 1655484557
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A17B6601E3}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases wake-up chance"
   Target_fr_fr "Augmente les chances de reprise de connaissance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_cs_cz "Zvyšuje pravděpodobnost probuzení se z bezvědomí"
   Target_ru_ru "Увеличивает вероятность пробуждения"
   Target_uk_ua "Збільшує ймовірність пробудження"
   Target_ko_kr "의식을 되찾을 확률 증가"
   Modified 1655484538
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60C8F66C4889FFD9}" {
   Id "ACE_Medical-InfoWidget_Morphine"
   Target_en_us "Alleviates severe pain"
   Target_fr_fr "Allège une douleur violente"
   Target_de_de "Lindert starke Schmerzen"
   Target_cs_cz "Zmírňuje silné bolesti"
   Target_ru_ru "Снимает сильную боль"
   Target_uk_ua "Знімає сильний біль"
   Target_ko_kr "극심한 통증 완화"
   Modified 1655484517
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{66D54CF8AFAC8A55}" {
   Id "ACE_Medical-InfoWidget_Splint"
   Target_en_us "Stabilizes fractures and speeds up healing"
   Target_de_de "Stabilisiert Frakturen und beschleunigt Heilung"
   Target_ko_kr "골절된 부위를 안정시키고 치유 속도를 높임"
   Modified 1725267534
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A0A9B86435}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to unconscious patients."
   Target_fr_fr "Administrée à des patients inconscients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_cs_cz "Aplikováno pacientům v bezvědomí."
   Target_ru_ru "Назначают пациентам без сознания."
   Target_uk_ua "Призначають пацієнтам без свідомості."
   Target_ko_kr "의식불명의 환자에게 투여합니다."
   Modified 1655484501
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{60CF45A0B47E9549}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_fr_fr "Adrénaline"
   Target_de_de "Epinephrin"
   Target_cs_cz "Epinefrin"
   Target_ru_ru "Инъекция адреналина"
   Target_uk_ua "Ін'єкція адреналіну"
   Target_ko_kr "에피네프린"
   Modified 1655484454
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{5E101C5589E004EE}" {
   Id "ACE_Medical-Item_Morphine_Description"
   Target_en_us "Administered to patients in severe pain."
   Target_fr_fr "Administrée à des patients ressentant une douleur violente."
   Target_de_de "Verabreicht an Patienten mit akuten Schmerzen."
   Target_cs_cz "Aplikováno pacientům v silných bolestech."
   Target_ru_ru "Назначают пациентам с сильной болью."
   Target_uk_ua "Призначають пацієнтам із сильним болем."
   Target_ko_kr "극심한 통증을 호소하는 환자에게 투여합니다."
   Modified 1655484454
   Author "kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{66D54CFA78569BA9}" {
   Id "ACE_Medical-Item_Splint_Description"
   Target_en_us "Applied to patients with fractures."
   Target_de_de "Angewandt an Patienten mit Frakturen."
   Target_ko_kr "골절을 당한 환자에게 사용됩니다."
   Modified 1725264660
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{66D54CFA7FD3D1D0}" {
   Id "ACE_Medical-Item_Splint_Name"
   Target_en_us "Splint"
   Target_de_de "Schiene"
   Target_ko_kr "부목"
   Modified 1725264203
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65515E08A4E02C61}" {
   Id "ACE_Medical-KeyBind_OpenRadialMenu"
   Target_en_us "Open medical radial menu"
   Target_de_de "Öffne medizinisches Kreismenü"
   Target_ko_kr "원형 의료 메뉴 열기"
   Modified 1699833171
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A9625D01268}" {
   Id "ACE_Medical-RadialMenu_ExaminePatient"
   Target_en_us "Examine patient"
   Target_de_de "Patient untersuchen"
   Target_ko_kr "환자 검사"
   Modified 1699834887
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A94855EB699}" {
   Id "ACE_Medical-RadialMenu_FluidReplacement"
   Target_en_us "Fluid Replacement"
   Target_de_de "Volumentherapie"
   Target_ko_kr "체액 복구"
   Modified 1699835500
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A967A9EA7B6}" {
   Id "ACE_Medical-RadialMenu_FractureManagement"
   Target_en_us "Fracture management"
   Target_de_de "Frakturbehandlung"
   Target_ko_kr "골절 관리"
   Modified 1699835013
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A94A58D1608}" {
   Id "ACE_Medical-RadialMenu_HemorrhageControl"
   Target_en_us "Hemorrhage control"
   Target_de_de "Blutstillung"
   Target_ko_kr "지혈"
   Modified 1699836091
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65516A97B16C0831}" {
   Id "ACE_Medical-RadialMenu_Medication"
   Target_en_us "Medication"
   Target_de_de "Medikation"
   Target_ko_kr "약물"
   Modified 1699835120
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{630D4CCE326184CA}" {
   Id "ACE_Medical-UserAction_BackPosition"
   Target_en_us "Put on back"
   Target_de_de "Auf den Rücken drehen"
   Target_ko_kr "똑바로 눕히기"
   Modified 1661817144
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{630D4CCE36458E06}" {
   Id "ACE_Medical-UserAction_LeftRecoveryPosition"
   Target_en_us "Put in left recovery position"
   Target_de_de "In linke Bewusstlosenlagerung bringen"
   Target_ko_kr "좌측으로 회복자세 교정하기"
   Modified 1694200390
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64FB538E9326BF80}" {
   Id "ACE_Medical-UserAction_RightRecoveryPosition"
   Target_en_us "Put in right recovery position"
   Target_de_de "In rechte Bewusstlosenlagerung bringen"
   Target_ko_kr "우측으로 회복자세 교정하기"
   Modified 1694200417
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{66D8267E58817461}" {
   Id "ACE_Medical-UserAction_UseSplint"
   Target_en_us "Use splint"
   Target_de_de "Schiene anwenden"
   Target_ko_kr "부목 사용하기"
   Modified 1725444110
   Author "Kexanone"
   LastChanged "Psycool"
  }
 }
}