StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65F8ED3623FB5254}" {
   Id "ACE_Overheating-AddonName"
   Target_en_us "Overheating"
   Target_kr_ko "과열"
   Modified 1710813523
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FD7BA74803598A}" {
   Id "ACE_Overheating-CheckBarrelTemperaturAction"
   Target_en_us "Check barrel temperature"
   Target_de_de "Lauftemperatur überprüfen"
   Target_kr_ko "총열 온도 확인"
   Modified 1711151729
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FE31FFE04C16AE}" {
   Id "ACE_Overheating-CoolBarrelInWaterAction"
   Target_en_us "Cool barrel in water"
   Target_de_de "Lauf im Wasser kühlen"
   Target_kr_ko "물로 총열 식히기"
   Modified 1711200065
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FD7BA71F3FB178}" {
   Id "ACE_Overheating-Notification_BARREL_TEMPERATURE_RESULT"
   Target_en_us "You find a barrel temperature of %1 °C"
   Target_de_de "Die Lauftemperatur liegt bei %1 °C"
   Target_kr_ko "총열의 온도가 %1 °C인 것을 확인했습니다."
   Modified 1711152715
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FD7BBCC39DF357}" {
   Id "ACE_Overheating-SwapBarrelAction"
   Target_en_us "Swap barrel"
   Target_de_de "Lauf austauschen"
   Target_kr_ko "총열 교체"
   Modified 1711153953
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65F8ED365BE1FB1F}" {
   Id "ACE_Overheating_TryClearWeaponJam"
   Target_en_us "Try clear weapon jam"
   Target_de_de "Versuche Waffenstörung zu beheben"
   Target_kr_ko "격발불량 해결 시도"
   Modified 1710813896
   Author "Kexanone"
   LastChanged "Psycool"
  }
 }
}