StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65F8ED3623FB5254}" {
   Id "ACE_Overheating-AddonName"
   Target_en_us "Overheating"
   Target_ko_kr "과열"
   Modified 1710813523
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FD7BA74803598A}" {
   Id "ACE_Overheating-CheckBarrelTemperaturAction"
   Target_en_us "Check barrel temperature"
   Target_de_de "Lauftemperatur überprüfen"
   Target_ko_kr "총열 온도 확인하기"
   Target_zh_cn "檢查槍管溫度"
   Modified 1711151729
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FE31FFE04C16AE}" {
   Id "ACE_Overheating-CoolBarrelInWaterAction"
   Target_en_us "Cool barrel in water"
   Target_de_de "Lauf im Wasser kühlen"
   Target_ko_kr "물로 총열 식히기"
   Target_zh_cn "用水冷卻槍管"
   Modified 1711200065
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{6A6563042671799D}" {
   Id "ACE_Overheating-Item_SpareBarrel_Description"
   Target_en_us "Spare barrel for machine guns."
   Target_de_de "Ersatzlauf für Maschinengewehre."
   Target_ko_kr "기관총 전용 예비 총열입니다."
   Modified 1785033252
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6A656304236C2E2B}" {
   Id "ACE_Overheating-Item_SpareBarrel_Name"
   Target_en_us "Spare Barrel"
   Target_de_de "Ersatzlauf"
   Target_ko_kr "예비 총열"
   Modified 1785033194
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{65FD7BA71F3FB178}" {
   Id "ACE_Overheating-Notification_BARREL_TEMPERATURE_RESULT"
   Target_en_us "You find a barrel temperature of %1 °C"
   Target_de_de "Die Lauftemperatur liegt bei %1 °C"
   Target_ko_kr "총열 온도가 %1 °C임을 알아냈습니다."
   Target_zh_cn "你測得槍管溫度為 %1 °C"
   Modified 1711152715
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65FD7BBCC39DF357}" {
   Id "ACE_Overheating-SwapBarrelAction"
   Target_en_us "Swap barrel"
   Target_de_de "Lauf austauschen"
   Target_ko_kr "총열 교체하기"
   Target_zh_cn "更換槍管"
   Modified 1711153953
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{65F8ED365BE1FB1F}" {
   Id "ACE_Overheating_TryClearWeaponJam"
   Target_en_us "Try clear weapon jam"
   Target_de_de "Versuche Waffenstörung zu beheben"
   Target_ko_kr "격발 불량 해결 시도하기"
   Target_zh_cn "嘗試排除卡彈"
   Modified 1710813896
   Author "Kexanone"
   LastChanged "Psycool"
  }
 }
}
