ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A6B671EB63761B5}" {
   m_sEntityPrefab "{8554ED3F088BADA6}Prefabs/Items/Equipment/Wirecutters/ACE_Wirecutters.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6A6B671EA89559F8}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 15
    }
   }
  }
 }
}