SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD58703CABF4}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{60FD565F7DFBE6A4}" {
     m_sEntityPrefab "{181B4ADA65725D59}Prefabs/Items/Core/ACE_Banana.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{60FD565F75061ED6}" {
       m_eItemType NON_LETHAL_THROWABLE
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{60FD565F20A453B3}" {
     m_sEntityPrefab "{9310D03C4A62286F}Prefabs/Weapons/Grenades/ACE_FragBanana.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{60FD565F5B120DC6}" {
       m_eItemType LETHAL_THROWABLE
       m_iSupplyCost 3
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69CF77A152A820B3}" {
     m_sEntityPrefab "{B9E98F1464E93A9E}Prefabs/Items/Equipment/Patches/ACE_AnvilPatch_GRS.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69CF77A157357A75}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69D0F4551A8D2A56}" {
     m_sEntityPrefab "{EDAF32E60741A6F1}Prefabs/Items/Equipment/Patches/ACE_MedicPatch_GRS.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69D0F4551A8D29F3}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}