SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453CA0B981}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD58703CABF4}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453B60C320}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453B27FB86}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D210804C2BFE9E}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D102AC05BFC4DC}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_InventoryItems_EntityCatalog_Equipment_USSR.conf" {
  }
 }
}