SCR_EntityCatalogMultiList {
 m_aMultiLists {
  ACE_EntityCatalogMultiListEntry "{69D210804C2BFE9E}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D102AC05BFC4DC}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_InventoryItems_EntityCatalog_Equipment_USSR.conf" {
  }
 }
}