StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6228B55EF02EBEDA}" {
   Id "ACE_Medical-AmmoniumCarbonatePackageAction"
   Target_en_us "Hold under nose"
   Target_de_de "Unter die Nase halten"
   Target_pt_br "Segure sob o nariz"
   Modified 1646854756
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B53ACDD034A6}" {
   Id "ACE_Medical-BloodState_Class1"
   Target_en_us "Class I hemorrhage"
   Target_de_de "Blutung Klasse 1"
   Target_pt_br "Hemorragia de Classe I"
   Modified 1646880476
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B53AC27D464E}" {
   Id "ACE_Medical-BloodState_Class2"
   Target_en_us "Class II hemorrhage"
   Target_de_de "Blutung Klasse 2"
   Target_pt_br "Hemorragia de Classe II"
   Modified 1646880471
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B53AC01F5452}" {
   Id "ACE_Medical-BloodState_Class3"
   Target_en_us "Class III hemorrhage"
   Target_de_de "Blutung Klasse 3"
   Target_pt_br "Hemorragia de Classe III"
   Modified 1646880460
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B53AC6AA6AB1}" {
   Id "ACE_Medical-BloodState_Class4"
   Target_en_us "Class IV hemorrhage"
   Target_de_de "Blutung Klasse 4"
   Target_pt_br "Hemorragia de Classe IV"
   Modified 1646880464
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55046CF7CC7}" {
   Id "ACE_Medical-CheckBloodPressureAction"
   Target_en_us "Check blood pressure"
   Target_de_de "Blutdruck überprüfen"
   Target_pt_br "Verificar pressão arterial"
   Modified 1646855701
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5504DC3E45E}" {
   Id "ACE_Medical-CheckPulseAction"
   Target_en_us "Check pulse"
   Target_de_de "Puls überprüfen"
   Target_pt_br "Verificar pulso"
   Modified 1646855641
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5503F479D0C}" {
   Id "ACE_Medical-CPRAction"
   Target_en_us "Perform CPR"
   Target_de_de "CPR durchführen"
   Target_pt_br "Realizar RCP"
   Modified 1646855683
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6230E5C2DA63508A}" {
   Id "ACE_Medical-Editor_TooltipDetail_VitalSigns_Name"
   Target_en_us "Vital signs"
   Target_de_de "Vitaldaten"
   Modified 1647372787
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55BAA8F501D}" {
   Id "ACE_Medical-InfoWidget_AmmoniumCarbonate"
   Target_en_us "Increases wake-up chance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_pt_br "Aumenta a chance de acordar"
   Modified 1646851976
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55BAE36450B}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases heart rate"
   Target_de_de "Erhöht die Herzfrequenz"
   Target_pt_br "Aumenta a frequência cardíaca"
   Modified 1646852181
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3A2AFEA00}" {
   Id "ACE_Medical-InfoWidget_KingLT"
   Target_en_us "Prevents obstruction and occlusion of airways"
   Target_de_de "Verhindert Obstruktion und Okklusion der Atemwege"
   Modified 1658280043
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55BA0A3E335}" {
   Id "ACE_Medical-InfoWidget_Metoprolol"
   Target_en_us "Decreases heart rate"
   Target_de_de "Sinkt die Herzfrequenz"
   Target_pt_br "Reduz a frequência cardíaca"
   Modified 1646852213
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55BA77C7538}" {
   Id "ACE_Medical-InfoWidget_Naloxone"
   Target_en_us "Antagonist for opioids like morphine"
   Target_de_de "Antagonist für Opioide wie Morphin"
   Target_pt_br "Antagonista para opioides como morfina"
   Modified 1646853322
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55BB2295B31}" {
   Id "ACE_Medical-InfoWidget_Phenylephrine"
   Target_en_us "Increases blood pressure and slows down bleeding and transfusion"
   Target_de_de "Erhöht den Blutdrucks und verlangsamt Blutung und Transfusion"
   Target_pt_br "Aumenta a pressão arterial e diminui o sangramento e transfusão"
   Modified 1646854172
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5586006E639}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Description"
   Target_en_us "Administered to unconscious patients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_pt_br "Administrado a pacientes inconscientes."
   Modified 1646851941
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5586D87363C}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Name"
   Target_en_us "Ammonium Carbonate"
   Target_de_de "Ammoniumcarbonat"
   Target_pt_br "Carbonato de Amônio"
   Modified 1646880521
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55B9B65D93A}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to patients in cardiac arrest"
   Target_de_de "Verabreicht an Patienten mit Herzstillstand"
   Target_pt_br "Administrado a pacientes em parada cardíaca"
   Modified 1646852903
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3AABB4BEF}" {
   Id "ACE_Medical-Item_KingLT_Description"
   Target_en_us "Airway management device inserted into throat"
   Target_de_de "Hilfsmittel zur Atemwegssicherung"
   Modified 1658286267
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3B0E7DA62}" {
   Id "ACE_Medical-Item_KingLT_Name"
   Target_en_us "King LT"
   Target_de_de "Larynxtubus"
   Modified 1658279424
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5585D442A6C}" {
   Id "ACE_Medical-Item_Metoprolol_Description"
   Target_en_us "Administered to patients with too high heart rate"
   Target_de_de "Verabreicht an Patienten mit überhöhter Herzfrequenz"
   Target_pt_br "Administrado a pacientes com frequência cardíaca muito alta"
   Modified 1646855760
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5585EEF5D9C}" {
   Id "ACE_Medical-Item_Metoprolol_Name"
   Target_en_us "Metoprolol"
   Target_de_de "Metoprolol"
   Target_pt_br "Metoprolol"
   Modified 1646852325
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5582C95F2EA}" {
   Id "ACE_Medical-Item_Naloxone_Description"
   Target_en_us "Administered to patients with opioid overdose"
   Target_de_de "Verabreicht an Patienten mit Opioidüberdosis"
   Target_pt_br "Administrado a pacientes com overdose de opioides"
   Modified 1646853271
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B558202D6005}" {
   Id "ACE_Medical-Item_Naloxone_Name"
   Target_en_us "Naloxone"
   Target_de_de "Naloxon"
   Target_pt_br "Naloxona"
   Modified 1646852315
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55877861E3A}" {
   Id "ACE_Medical-Item_Phenylephrine_Description"
   Target_en_us "Administered to patients for raising blood pressure"
   Target_de_de "Verabreicht an Patienten um den Blutdruck zu erhöhen"
   Target_pt_br "Administrado a pacientes para elevar a pressão arterial"
   Modified 1646854236
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55875DE022F}" {
   Id "ACE_Medical-Item_Phenylephrine_Name"
   Target_en_us "Phenylephrine"
   Target_de_de "Phenylephrin"
   Target_pt_br "Fenilefrina"
   Modified 1646852334
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55ED01FBD98}" {
   Id "ACE_Medical-MetoprololInjectionAction"
   Target_en_us "Inject metoprolol"
   Target_de_de "Metoprolol injizieren"
   Target_pt_br "Injetar metoprolol"
   Modified 1646854607
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55ECF6624E9}" {
   Id "ACE_Medical-NaloxoneInjectionAction"
   Target_en_us "Inject naloxone"
   Target_de_de "Naloxon injizieren"
   Target_pt_br "Injetar naloxona"
   Modified 1646854603
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55235D38AF1}" {
   Id "ACE_Medical-Notification_BLOOD_PRESSURE_RESULT"
   Target_en_us "You find a blood pressure of %1/%2 mmHg"
   Target_de_de "Der Blutdruck liegt bei %1/%2 mmHg"
   Target_pt_br "pressão arterial em %1/%2 mmHg"
   Modified 1646856521
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B5523F76CF1E}" {
   Id "ACE_Medical-Notification_PULSE_RESULT"
   Target_en_us "You find a heart rate of %1"
   Target_de_de "Herzfrequenz ist %1"
   Target_pt_br "Frequência cardíaca em %1"
   Modified 1646856451
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754FA15390F40}" {
   Id "ACE_Medical-Notification_SPO2_RESULT"
   Target_en_us "You find a SpO2 of %1%"
   Target_de_de " SpO2 ist %1%"
   Modified 1658284253
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6228B55ED9DB4B14}" {
   Id "ACE_Medical-PhenylephrineInjectionAction"
   Target_en_us "Inject phenylephrine"
   Target_de_de "Phenylephrin injizieren"
   Target_pt_br "Injetar fenilefrina"
   Modified 1646856204
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F97D23F840}" {
   Id "ACE_Medical-UserAction_CheckBloodPressure"
   Target_en_us "Check blood pressure"
   Target_de_de "Blutdruck bestimmen"
   Modified 1658284424
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F92539C689}" {
   Id "ACE_Medical-UserAction_CheckPulse"
   Target_en_us "Check pulse"
   Target_de_de "Puls bestimmen"
   Modified 1658284435
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F96369C7F7}" {
   Id "ACE_Medical-UserAction_CheckSpO2"
   Target_en_us "Check SpO2"
   Target_de_de "SpO2 bestimmen"
   Modified 1658284451
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}