StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6228B55EF02EBEDA}" {
   Id "ACE_Medical-AmmoniumCarbonatePackageAction"
   Target_en_us "Hold under nose"
   Target_fr_fr "Mettre sous le nez"
   Target_de_de "Unter die Nase halten"
   Target_pt_br "Segure sob o nariz"
   Modified 1656914080
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B53ACDD034A6}" {
   Id "ACE_Medical-BloodState_Class1"
   Target_en_us "Class I hemorrhage"
   Target_fr_fr "Hémorragie de Classe I"
   Target_de_de "Blutung Klasse 1"
   Target_pt_br "Hemorragia de Classe I"
   Modified 1656914068
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B53AC27D464E}" {
   Id "ACE_Medical-BloodState_Class2"
   Target_en_us "Class II hemorrhage"
   Target_fr_fr "Hémorragie de Classe II"
   Target_de_de "Blutung Klasse 2"
   Target_pt_br "Hemorragia de Classe II"
   Modified 1656914053
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B53AC01F5452}" {
   Id "ACE_Medical-BloodState_Class3"
   Target_en_us "Class III hemorrhage"
   Target_fr_fr "Hémorragie de Classe III"
   Target_de_de "Blutung Klasse 3"
   Target_pt_br "Hemorragia de Classe III"
   Modified 1656914036
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B53AC6AA6AB1}" {
   Id "ACE_Medical-BloodState_Class4"
   Target_en_us "Class IV hemorrhage"
   Target_fr_fr "Hémorragie de Classe IV"
   Target_de_de "Blutung Klasse 4"
   Target_pt_br "Hemorragia de Classe IV"
   Modified 1656914016
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55046CF7CC7}" {
   Id "ACE_Medical-CheckBloodPressureAction"
   Target_en_us "Check blood pressure"
   Target_fr_fr "Contrôler la pression artérielle"
   Target_de_de "Blutdruck überprüfen"
   Target_pt_br "Verificar pressão arterial"
   Modified 1656913939
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5504DC3E45E}" {
   Id "ACE_Medical-CheckPulseAction"
   Target_en_us "Check pulse"
   Target_fr_fr "Contrôler le pouls"
   Target_de_de "Puls überprüfen"
   Target_pt_br "Verificar pulso"
   Modified 1656913922
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5503F479D0C}" {
   Id "ACE_Medical-CPRAction"
   Target_en_us "Perform CPR"
   Target_fr_fr "Pratiquer une RCP"
   Target_de_de "CPR durchführen"
   Target_pt_br "Realizar RCP"
   Modified 1656913953
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6230E5C2DA63508A}" {
   Id "ACE_Medical-Editor_TooltipDetail_VitalSigns_Name"
   Target_en_us "Vital signs"
   Target_fr_fr "Signes vitaux"
   Target_de_de "Vitaldaten"
   Target_pt_br "Sinais vitais"
   Modified 1656913627
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55BAA8F501D}" {
   Id "ACE_Medical-InfoWidget_AmmoniumCarbonate"
   Target_en_us "Increases wake-up chance"
   Target_fr_fr "Augmente les chances de reprise de connaissance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_pt_br "Aumenta a chance de acordar"
   Modified 1656913614
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55BAE36450B}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases heart rate"
   Target_fr_fr "Augmente la fréquence cardiaque"
   Target_de_de "Erhöht die Herzfrequenz"
   Target_pt_br "Aumenta a frequência cardíaca"
   Modified 1656913587
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55BA0A3E335}" {
   Id "ACE_Medical-InfoWidget_Metoprolol"
   Target_en_us "Decreases heart rate"
   Target_fr_fr "Diminue la fréquence cardiaque"
   Target_de_de "Sinkt die Herzfrequenz"
   Target_pt_br "Reduz a frequência cardíaca"
   Modified 1656913483
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55BA77C7538}" {
   Id "ACE_Medical-InfoWidget_Naloxone"
   Target_en_us "Antagonist for opioids like morphine"
   Target_fr_fr "Antidote aux opioïdes (ex. : morphine)"
   Target_de_de "Antagonist für Opioide wie Morphin"
   Target_pt_br "Antagonista para opioides como morfina"
   Modified 1656913466
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55BB2295B31}" {
   Id "ACE_Medical-InfoWidget_Phenylephrine"
   Target_en_us "Increases blood pressure and slows down bleeding and transfusion"
   Target_fr_fr "Augmente la pression artérielle et ralentit le saignement ainsi que la transfusion"
   Target_de_de "Erhöht den Blutdrucks und verlangsamt Blutung und Transfusion"
   Target_pt_br "Aumenta a pressão arterial e diminui o sangramento e transfusão"
   Modified 1656913452
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5586006E639}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Description"
   Target_en_us "Administered to unconscious patients."
   Target_fr_fr "Pour patients inconscients"
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_pt_br "Administrado a pacientes inconscientes."
   Modified 1656913435
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5586D87363C}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Name"
   Target_en_us "Ammonium Carbonate"
   Target_fr_fr "Carbonate d’ammonium"
   Target_de_de "Ammoniumcarbonat"
   Target_pt_br "Carbonato de Amônio"
   Modified 1656913419
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55B9B65D93A}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to patients in cardiac arrest"
   Target_fr_fr "Pour patients en arrêt cardiaque"
   Target_de_de "Verabreicht an Patienten mit Herzstillstand"
   Target_pt_br "Administrado a pacientes em parada cardíaca"
   Modified 1656913398
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5585D442A6C}" {
   Id "ACE_Medical-Item_Metoprolol_Description"
   Target_en_us "Administered to patients with too high heart rate"
   Target_fr_fr "Pour patients avec fréquence cardiaque trop élevée"
   Target_de_de "Verabreicht an Patienten mit überhöhter Herzfrequenz"
   Target_pt_br "Administrado a pacientes com frequência cardíaca muito alta"
   Modified 1656913384
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5585EEF5D9C}" {
   Id "ACE_Medical-Item_Metoprolol_Name"
   Target_en_us "Metoprolol"
   Target_fr_fr "Métoprolol"
   Target_de_de "Metoprolol"
   Target_pt_br "Metoprolol"
   Modified 1656913369
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B5582C95F2EA}" {
   Id "ACE_Medical-Item_Naloxone_Description"
   Target_en_us "Administered to patients with opioid overdose"
   Target_fr_fr "En cas de surdose d’opioïdes"
   Target_de_de "Verabreicht an Patienten mit Opioidüberdosis"
   Target_pt_br "Administrado a pacientes com overdose de opioides"
   Modified 1656913355
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B558202D6005}" {
   Id "ACE_Medical-Item_Naloxone_Name"
   Target_en_us "Naloxone"
   Target_fr_fr "Naloxone"
   Target_de_de "Naloxon"
   Target_pt_br "Naloxona"
   Modified 1656913330
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55877861E3A}" {
   Id "ACE_Medical-Item_Phenylephrine_Description"
   Target_en_us "Administered to patients for raising blood pressure"
   Target_fr_fr "Pour augmenter la pression artérielle"
   Target_de_de "Verabreicht an Patienten um den Blutdruck zu erhöhen"
   Target_pt_br "Administrado a pacientes para elevar a pressão arterial"
   Modified 1656913312
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55875DE022F}" {
   Id "ACE_Medical-Item_Phenylephrine_Name"
   Target_en_us "Phenylephrine"
   Target_fr_fr "Phényléphrine"
   Target_de_de "Phenylephrin"
   Target_pt_br "Fenilefrina"
   Modified 1656913298
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55ED01FBD98}" {
   Id "ACE_Medical-MetoprololInjectionAction"
   Target_en_us "Inject metoprolol"
   Target_fr_fr "Injecter du métoprolol"
   Target_de_de "Metoprolol injizieren"
   Target_pt_br "Injetar metoprolol"
   Modified 1656914095
   Author "Kexanone"
   LastChanged "claud"
  }
  CustomStringTableItem "{6228B55ECF6624E9}" {
   Id "ACE_Medical-NaloxoneInjectionAction"
   Target_en_us "Inject naloxone"
   Target_fr_fr "Injecter de la naloxone"
   Target_de_de "Naloxon injizieren"
   Target_pt_br "Injetar naloxona"
   Modified 1656913250
   Author "Kexanone"
   LastChanged "claud"
  }
 }
}
