ACE_SettingsConfig {
 m_aInitialModSettings {
  ACE_Medical_Circulation_Settings "{65D2FB432916B718}" {
   m_bCardiacArrestForAIEnabled 1
  }
  ACE_Medical_Defibrillation_Defibrillation_Settings "{68440A2A7EA03E86}" {
  }
 }
}