StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5DDEFB516A0DA608}" {
   Id "ACE_Carrying-AddonName"
   Target_en_us "ACE - Carrying"
   Modified 1630934708
   Author "kexanone"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{5DDEFB51C773DDD9}" {
   Id "ACE_Carrying-UserAction_Carry"
   Target_en_us "Carry"
   Target_fr_fr "Porter"
   Target_de_de "Tragen"
   Target_cs_cz "Nést"
   Target_pl_pl "Podnieś"
   Modified 1630934696
   Author "kexanone"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{5E0C2A71118B03B7}" {
   Id "ACE_Carrying-UserAction_Carrying"
   Target_en_us "Carrying"
   Target_fr_fr "Porter"
   Target_de_de "Am Tragen"
   Target_cs_cz "Nošení"
   Target_pl_pl "Noszenie"
   Modified 1630934692
   Author "kexanone"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{613521B70C031A0D}" {
   Id "ACE_Carrying-UserAction_PlaceCasualty"
   Target_en_us "Place casualty"
   Target_pl_pl "Połóż rannego"
   Modified 1630934649
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{5E0EB8A9BCC4201E}" {
   Id "ACE_Carrying-UserAction_Release"
   Target_en_us "Release"
   Target_fr_fr "Déposer"
   Target_de_de "Ablegen"
   Target_cs_cz "Položit"
   Target_pl_pl "Połóż"
   Modified 1630934677
   Author "kexanone"
   LastChanged "filip"
  }
 }
}