StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64AD374154331C4C}" {
   Id "ACE_Carrying-UserAction_Drag"
   Target_en_us "Drag"
   Target_fr_fr "Traîner"
   Target_it_it "Trascina"
   Target_de_de "Ziehen"
   Target_es_es "Arrastrar"
   Target_cs_cz "Táhnout"
   Target_pl_pl "Ciągnij"
   Target_ru_ru "Тащить"
   Target_ja_jp "引きずる"
   Target_ko_kr "끌기"
   Target_pt_br "Arrastar"
   Target_zh_cn "拖行"
   Modified 1770600721
   Author "Kex"
   LastChanged "wilso"
  }
  CustomStringTableItem "{69876CC234E07E0D}" {
   Id "ACE_Carrying-UserAction_Pull"
   Target_en_us "Pull"
   Target_en_us_edited "Pull"
   Comment "Pull / Tug a body behind you"
   Modified 1770601531
   Author "wilso"
   LastChanged "wilso"
  }
 }
}