StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64AD374154331C4C}" {
   Id "ACE_Carrying-UserAction_Drag"
   Target_en_us "Drag"
   Target_fr_fr "Traîner"
   Target_it_it "Trascina"
   Target_de_de "Ziehen"
   Target_es_es "Arrastrar"
   Target_cs_cz "Táhnout"
   Target_pl_pl "Ciągnij"
   Target_ru_ru "Тащить"
   Target_ja_jp "引きずる"
   Target_ko_kr "끌기"
   Target_pt_br "Arrastar"
   Target_zh_cn "拖行"
   Modified 1725224988
   Author "Kex"
   LastChanged "YuanYu"
  }
 }
}
