StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5DDEFB516A0DA608}" {
   Id "CEN_CarrierSystem-AddonName"
   Target_en_us "CEN - Carrier System"
   Modified 1578023399
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5DDEFB51C773DDD9}" {
   Id "CEN_CarrierSystem-UserAction_Carry"
   Target_en_us "Carry"
   Target_fr_fr "Porter"
   Target_de_de "Tragen"
   Modified 1574895272
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5E0C2A71118B03B7}" {
   Id "CEN_CarrierSystem-UserAction_Carrying"
   Target_en_us "Carrying"
   Target_fr_fr "Porter"
   Target_de_de "Am Tragen"
   Modified 1577870149
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5E0EB8A9BCC4201E}" {
   Id "CEN_CarrierSystem-UserAction_Release"
   Target_en_us "Release"
   Target_fr_fr "Déposer"
   Target_de_de "Ablegen"
   Modified 1578028452
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}