StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60EE977D3F616C5F}" {
   Id "ACE_Finger-Notification_PlayerPointsAtEntity"
   Target_en_us "%1 points at %2"
   Target_fr_fr "%1 désigne %2"
   Target_de_de "%1 zeigt auf %2"
   Target_cs_cz "%1 ukazuje na %2"
   Target_ru_ru "%1 указывает на %2"
   Target_uk_ua "%1 вказує на %2"
   Modified 1655484088
   Author "kexanone"
   LastChanged "Smith"
  }
  CustomStringTableItem "{60EE977D0262C356}" {
   Id "ACE_Finger-Notification_PlayerPointsAtPosition"
   Target_en_us "%1 points at position"
   Target_fr_fr "%1 indique une position"
   Target_de_de "%1 zeigt auf eine Position"
   Target_cs_cz "%1 ukazuje na pozici"
   Target_ru_ru "%1 указывает на позицию"
   Target_uk_ua "%1 вказує на позицію"
   Modified 1655484054
   Author "kexanone"
   LastChanged "Smith"
  }
 }
}
