StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60EE977D3F616C5F}" {
   Id "ACE_Finger-Notification_PlayerPointsAtEntity"
   Target_en_us "%1 points at %2"
   Target_de_de "%1 zeigt auf %2"
   Target_cs_cz "%1 ukazuje na %2"
   Modified 1626252576
   Author "kexanone"
   LastChanged "apollo-jk"
  }
  CustomStringTableItem "{60EE977D0262C356}" {
   Id "ACE_Finger-Notification_PlayerPointsAtPosition"
   Target_en_us "%1 points at position"
   Target_de_de "%1 zeigt auf eine Position"
   Target_cs_cz "%1 ukazuje na pozici"
   Modified 1626252568
   Author "kexanone"
   LastChanged "apollo-jk"
  }
 }
}