StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{649378D01FD98890}" {
   Id "ACE-Explosives_FailReason_Buried"
   Target_en_us "Buried"
   Target_it_it "Sepolto"
   Target_de_de "Eingegraben"
   Target_es_es "Enterrado"
   Target_ko_kr "매설됨"
   Target_pt_br "Enterrado"
   Target_zh_cn "已埋設"
   Modified 1750691276
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{649378D2BB5531A1}" {
   Id "ACE-Explosives_FailReason_HardSurface"
   Target_en_us "Hard surface"
   Target_it_it "Superficie dura"
   Target_de_de "Harte Oberfläche"
   Target_es_es "Superficie dura"
   Target_ko_kr "단단한 지면"
   Target_pt_br "Superfície dura"
   Target_zh_cn "硬質地面（不可挖掘）"
   Modified 1750691286
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{64933B9C7DC48AD7}" {
   Id "ACE-Explosives_UserAction_Bury_Name"
   Target_en_us "Bury"
   Target_it_it "Seppellire"
   Target_de_de "Eingraben"
   Target_es_es "Enterrar"
   Target_ko_kr "매설"
   Target_pt_br "Enterrar"
   Target_zh_cn "埋設"
   Modified 1750691295
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{61B80DDD1907B555}" {
   Id "ACE-Explosives_UserAction_Disarm_Name"
   Target_en_us "Disarm"
   Target_it_it "Disarmare"
   Target_de_de "Entschärfen"
   Target_es_es "Desarmar"
   Target_ko_kr "해체하기"
   Target_pt_br "Desarmar"
   Target_zh_cn "解除"
   Modified 1750691342
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
  CustomStringTableItem "{64933B9C711A2AC1}" {
   Id "ACE-Explosives_UserAction_Unbury_Name"
   Target_en_us "Unbury"
   Target_it_it "Dissotterrare"
   Target_de_de "Ausgraben"
   Target_es_es "Desenterrar"
   Target_ko_kr "꺼내기"
   Target_pt_br "Desenterrar"
   Target_zh_cn "挖出"
   Modified 1750691350
   Author "Kex"
   LastChanged "KingDaddyBoyz"
  }
 }
}