StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{649378D01FD98890}" {
   Id "ACE-Explosives_FailReason_Buried"
   Target_en_us "Buried"
   Target_de_de "Eingegraben"
   Modified 1687423940
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{649378D2BB5531A1}" {
   Id "ACE-Explosives_FailReason_HardSurface"
   Target_en_us "Hard surface"
   Target_de_de "Harte Oberfläche"
   Modified 1687424525
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{64933B9C7DC48AD7}" {
   Id "ACE-Explosives_UserAction_Bury_Name"
   Target_en_us "Bury"
   Target_de_de "Eingraben"
   Modified 1687384945
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{61B80DDD1907B555}" {
   Id "ACE-Explosives_UserAction_Disarm_Name"
   Target_en_us "Disarm"
   Target_de_de "Entschärfen"
   Modified 1687384761
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{64933B9C711A2AC1}" {
   Id "ACE-Explosives_UserAction_Unbury_Name"
   Target_en_us "Unbury"
   Target_de_de "Ausgraben"
   Modified 1687384951
   Author "Kex"
   LastChanged "Kex"
  }
 }
}