StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{649378D01FD98890}" {
   Id "ACE-Explosives_FailReason_Buried"
   Target_en_us "Buried"
   Target_de_de "Eingegraben"
   Target_zh_cn "已埋設"
   Target_ko_kr "매설됨"
   Modified 1725225261
   Author "Kex"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{649378D2BB5531A1}" {
   Id "ACE-Explosives_FailReason_HardSurface"
   Target_en_us "Hard surface"
   Target_de_de "Harte Oberfläche"
   Target_zh_cn "硬質地面（不可挖掘）"
   Target_ko_kr "단단한 지면"
   Modified 1725496107
   Author "Kex"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64933B9C7DC48AD7}" {
   Id "ACE-Explosives_UserAction_Bury_Name"
   Target_en_us "Bury"
   Target_de_de "Eingraben"
   Target_zh_cn "埋設"
   Target_ko_kr "매설"
   Modified 1725495938
   Author "Kex"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{61B80DDD1907B555}" {
   Id "ACE-Explosives_UserAction_Disarm_Name"
   Target_en_us "Disarm"
   Target_de_de "Entschärfen"
   Target_zh_cn "解除"
   Target_ko_kr "해체하기"
   Modified 1725495889
   Author "Kex"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64933B9C711A2AC1}" {
   Id "ACE-Explosives_UserAction_Unbury_Name"
   Target_en_us "Unbury"
   Target_de_de "Ausgraben"
   Target_zh_cn "挖出"
   Target_ko_kr "꺼내기"
   Modified 1725496037
   Author "Kex"
   LastChanged "Psycool"
  }
 }
}
