ACE_EntityCatalogMultiListEntry : "{0AFC873567388CDE}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Equipment.conf" {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69FF5E56428E3286}" {
   m_sEntityPrefab "{BD319DE81806E4A0}Prefabs/Items/Misc/ACE_SandbagContainer_USSR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69FF5E564170D45B}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 30
    }
   }
  }
 }
}