ACE_EntityCatalogMultiListEntry : "{0AFC873567388CDE}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Equipment.conf" {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69FF5E5624E5F9AC}" {
   m_sEntityPrefab "{25C084725870741B}Prefabs/Items/Misc/ACE_SandbagContainer_US.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69FF5E565874F4AB}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 30
    }
   }
  }
 }
}