StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{670D1E431FCABE53}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_big_Name"
   Target_en_us "Personal Trench (Big)"
   Target_de_de "Schützengraben (Groß)"
   Modified 1728932352
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D4C2495CF93FE}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_giant_Name"
   Target_en_us "Personal Trench (Giant)"
   Target_de_de "Schützengraben (Sehr Groß)"
   Modified 1728932416
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D1E4311B468FB}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_small_Name"
   Target_en_us "Personal Trench (Small)"
   Target_de_de "Schützengraben (Klein)"
   Modified 1728932294
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D1E4318FD977F}" {
   Id "ACE_Trenches-EditableEntity_TrenchSegment_01_short_Name"
   Target_en_us "Trench Segment (Short)"
   Target_de_de "Grabensegment (Kurz)"
   Modified 1728932475
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}