StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{670D1E431FCABE53}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_big_Name"
   Target_en_us "Personal Trench (Big)"
   Target_de_de "Schützengraben (Groß)"
   Target_zh_cn "個人戰壕（大型）"
   Modified 1730463497
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{670D4C2495CF93FE}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_giant_Name"
   Target_en_us "Personal Trench (Giant)"
   Target_de_de "Schützengraben (Sehr Groß)"
   Target_zh_cn "個人戰壕（巨型）"
   Modified 1730463510
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{670D1E4311B468FB}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_small_Name"
   Target_en_us "Personal Trench (Small)"
   Target_de_de "Schützengraben (Klein)"
   Target_zh_cn "個人戰壕（小型）"
   Modified 1730463520
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{670D1E4318FD977F}" {
   Id "ACE_Trenches-EditableEntity_TrenchSegment_01_short_Name"
   Target_en_us "Trench Segment (Short)"
   Target_de_de "Grabensegment (Kurz)"
   Target_zh_cn "戰壕段（短）"
   Modified 1730463528
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{670D6BA9CAA8072A}" {
   Id "ACE_Trenches-EditableEntity_VehicleTrench_01_Name"
   Target_en_us "Vehicle Trench"
   Target_de_de "Fahrzeug Schützengraben"
   Target_zh_cn "載具戰壕"
   Modified 1730463537
   Author "Kexanone"
   LastChanged "YuanYu"
  }
 }
}
