StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{670D1E431FCABE53}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_big_Name"
   Target_en_us "Personal Trench (Big)"
   Target_de_de "Schützengraben (Groß)"
   Target_ko_kr "개인용 참호 (대형)"
   Modified 1728932352
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D4C2495CF93FE}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_giant_Name"
   Target_en_us "Personal Trench (Giant)"
   Target_de_de "Schützengraben (Sehr Groß)"
   Target_ko_kr "개인용 참호 (초대형)"
   Modified 1728932416
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D1E4311B468FB}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_small_Name"
   Target_en_us "Personal Trench (Small)"
   Target_de_de "Schützengraben (Klein)"
   Target_ko_kr "개인용 참호 (소형)"
   Modified 1728932294
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D1E4318FD977F}" {
   Id "ACE_Trenches-EditableEntity_TrenchSegment_01_short_Name"
   Target_en_us "Trench Segment (Short)"
   Target_de_de "Grabensegment (Kurz)"
   Target_ko_kr "부분 참호 (짧음)"
   Modified 1728932475
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{670D6BA9CAA8072A}" {
   Id "ACE_Trenches-EditableEntity_VehicleTrench_01_Name"
   Target_en_us "Vehicle Trench"
   Target_de_de "Fahrzeug Schützengraben"
   Target_ko_kr "차량용 참호"
   Modified 1728935966
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{69FF5E55F8D175DB}" {
   Id "ACE_Trenches-Item_SandbagContainer_Description"
   Target_en_us "Storage container for transporting empty sandbags."
   Target_de_de "Behälter zum Transportieren von leeren Sandsäcken."
   Target_ko_kr "빈 모래주머니를 운반하기 위한 보관함입니다."
   Modified 1778349492
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{69FF5E55FEC70DF4}" {
   Id "ACE_Trenches-Item_SandbagContainer_Name"
   Target_en_us "Sandbag Container"
   Target_de_de "Sandsackbehälter"
   Target_ko_kr "모래주머니 보관함"
   Modified 1778345374
   Author "Kex"
   LastChanged "Kex"
  }
 }
}