SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA2B2FF4}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D102AC212B4389}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D2108069E4B053}" : "{12790B4E7D42F952}Configs/EntityCatalog/US/ACE_InventoryItems_EntityCatalog_Equipment_US.conf" {
  }
 }
}