SCR_AvailableActionsDisplay {
 m_aActions {
  SCR_HeldItemAvailableActionContext "{69AD033978F5B199}" {
   m_aConditions {
    SCR_CharacterHasConsumableItemEquippedCondition "{69AD0339901C40A7}" {
     m_eConsumableType ACE_MEDICAL_HEATPACK
    }
   }
   m_sTag "ACE_CHARACTER_HEATPACK_APPLY"
   m_sAction "GadgetActivate"
   m_sName "#ACE_Medical-Heatpack-Apply-Action"
  }
 }
}