SCR_PlayerCommandsConfig {
 m_aCommands {
  ACE_MetalClangingCommand "{69D549B40AA7B09D}" {
   m_sCommandName "ACE_MetalClanging"
   m_sCommandDisplayName "#ACE-Emotes_Emote_MetalClanging_Name"
   m_sIconName "warning"
  }
 }
}