SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{610AD5372D760250}" {
  m_aElements {
   SCR_PlayerCommandingMenuCategoryElement "{691A750B40987DA4}" {
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{69FB2DF989A10920}" {
      m_sCommandName "CMD_ACE_MetalClanging"
     }
    }
   }
  }
 }
}