StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62D754F3A2AFEA00}" {
   Id "ACE_Medical-InfoWidget_KingLT"
   Target_en_us "Prevents obstruction and occlusion of airways"
   Target_de_de "Verhindert Obstruktion und Okklusion der Atemwege"
   Modified 1658280043
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3AABB4BEF}" {
   Id "ACE_Medical-Item_KingLT_Description"
   Target_en_us "Airway management device inserted into throat"
   Target_de_de "Hilfsmittel zur Atemwegssicherung"
   Modified 1658286267
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3B0E7DA62}" {
   Id "ACE_Medical-Item_KingLT_Name"
   Target_en_us "King LT"
   Target_de_de "Larynxtubus"
   Modified 1658279424
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{63112656052CFC80}" {
   Id "ACE_Medical-UserAction_ChestSeal"
   Target_en_us "Use chest seal"
   Target_de_de "Thorax Pflaster anwenden"
   Modified 1662077541
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6311265639790D08}" {
   Id "ACE_Medical-UserAction_KingLT"
   Target_en_us "Insert King LT"
   Target_de_de "Larynxtubus einsetzen"
   Modified 1662077451
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6311265606824A7E}" {
   Id "ACE_Medical-UserAction_NeedleDecompression"
   Target_en_us "Perform needle decompression"
   Target_de_de "Nadeldekompression durchführen"
   Modified 1662077408
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}