StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64FF4A203D8FE526}" {
   Id "ACE_Medical-InfoWidget_ChestSeal"
   Target_en_us "Prevents tension pneumothorax"
   Target_de_de "Verhindert die Bildung einer Spannungspneumothorax"
   Target_zh_cn "預防張力性氣胸"
   Modified 1730464160
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{62D754F3A2AFEA00}" {
   Id "ACE_Medical-InfoWidget_KingLT"
   Target_en_us "Prevents obstruction and occlusion of airways"
   Target_de_de "Verhindert Obstruktion und Okklusion der Atemwege"
   Target_zh_cn "預防氣道阻塞與閉塞"
   Modified 1730464171
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A2623C65D0D}" {
   Id "ACE_Medical-InfoWidget_NCDKit"
   Target_en_us "Used for treating tension pneumothorax"
   Target_de_de "Zum Behandeln von Spannungspneumothorax"
   Target_zh_cn "用於治療張力性氣胸"
   Modified 1730464192
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A23ED61E92B}" {
   Id "ACE_Medical-InfoWidget_OxygenMask"
   Target_en_us "Provides supplemental oxygen"
   Target_de_de "Sauerstoff zuführen"
   Target_zh_cn "提供輔助供氧"
   Modified 1730464306
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A20D0C03B3A}" {
   Id "ACE_Medical-Item_ChestSeal_Description"
   Target_en_us "Special dressing for open chest wounds"
   Target_de_de "Spezialverband für offenen Brustkorbverletzungen"
   Target_zh_cn "胸壁開放傷口封閉敷料"
   Modified 1730464593
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A20DDF8616D}" {
   Id "ACE_Medical-Item_ChestSeal_Name"
   Target_en_us "Chest Seal"
   Target_de_de "Thorax Pflaster"
   Target_zh_cn "胸壁封閉敷料"
   Modified 1730464545
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{62D754F3AABB4BEF}" {
   Id "ACE_Medical-Item_KingLT_Description"
   Target_en_us "Airway management device inserted into throat"
   Target_de_de "Hilfsmittel zur Atemwegssicherung"
   Target_zh_cn "聲門上呼吸道裝置"
   Modified 1730465029
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{62D754F3B0E7DA62}" {
   Id "ACE_Medical-Item_KingLT_Name"
   Target_en_us "King LT"
   Target_de_de "Larynxtubus"
   Target_zh_cn "King LT 喉管"
   Modified 1730465082
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A2633C94C03}" {
   Id "ACE_Medical-Item_NCDKit_Description"
   Target_en_us "Kit for performing needle decompression"
   Target_de_de "Set zur Durchführung von Nadeldekompression"
   Target_zh_cn "針刺減壓套件"
   Modified 1730465152
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A263E864FA9}" {
   Id "ACE_Medical-Item_NCDKit_Name"
   Target_en_us "NCD Kit"
   Target_de_de "Dekompressionsnadelset"
   Target_zh_cn "NCD Kit 非傳染病救援包"
   Modified 1730465255
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A23362FB915}" {
   Id "ACE_Medical-Item_OxygenMask_Description"
   Target_en_us "Mask for oxygen therapy"
   Target_de_de "Maske für Sauerstofftherapie"
   Target_zh_cn "氧氣治療面罩"
   Modified 1730465294
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A2335B51A2F}" {
   Id "ACE_Medical-Item_OxygenMask_Name"
   Target_en_us "Oxygen Mask"
   Target_de_de "Sauerstoffmaske"
   Target_zh_cn "氧氣面罩"
   Modified 1730465313
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{671625C94FF978B0}" {
   Id "ACE_Medical-Notification_BREATHING_RESULT"
   Target_en_us "You find a respiratory rate of %1 breaths per minute"
   Target_de_de "Die Atemfrequenz ist %1 AZ/min"
   Target_zh_cn "您測得的呼吸速率是每分鐘 %1 次"
   Modified 1730465358
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{62D754FA15390F40}" {
   Id "ACE_Medical-Notification_SPO2_RESULT"
   Target_en_us "You find a SpO2 of %1%"
   Target_de_de " SpO2 ist %1%"
   Target_zh_cn "您測得的血氧飽和度 (SpSpO2) 是 %1%"
   Modified 1730465454
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{671D563325641152}" {
   Id "ACE_Medical-OpenPneumothorax"
   Target_en_us "Open pneumothorax"
   Target_de_de "Offener Pneumothorax"
   Target_zh_cn "開放性氣胸"
   Modified 1730352105
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6559386744A11E53}" {
   Id "ACE_Medical-RadialMenu_AirwayThoraxManagement"
   Target_en_us "Airway/Thorax management"
   Target_de_de "Atemweg/Brustkorb Versorgung"
   Target_zh_cn "氣道與胸廓管理"
   Modified 1730465868
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{671D5633273D3233}" {
   Id "ACE_Medical-TensionPneumothorax"
   Target_en_us "Tension pneumothorax"
   Target_de_de "Spannungspneumothorax"
   Target_zh_cn "張力性氣胸"
   Modified 1730465888
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{671625C89F878900}" {
   Id "ACE_Medical-UserAction_CheckBreathing"
   Target_en_us "Check respiratory rate"
   Target_de_de "Atemfrequenz überprüfen"
   Target_zh_cn "測量呼吸速率"
   Modified 1730465924
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{62D754F96369C7F7}" {
   Id "ACE_Medical-UserAction_CheckSpO2"
   Target_en_us "Check SpO2"
   Target_de_de "SpO2 bestimmen"
   Target_zh_cn "測量血氧飽和度 (SpSpO2)"
   Modified 1730465994
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{63112656052CFC80}" {
   Id "ACE_Medical-UserAction_ChestSeal"
   Target_en_us "Use chest seal"
   Target_de_de "Thorax Pflaster anwenden"
   Target_zh_cn "使用胸壁封閉敷料"
   Modified 1730466077
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6719486F0C433459}" {
   Id "ACE_Medical-UserAction_ClearVomit"
   Target_en_us "Clear vomit"
   Target_de_de "Erbrochenes entfernen"
   Target_zh_cn "清理嘔吐物"
   Modified 1730466106
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6311265639790D08}" {
   Id "ACE_Medical-UserAction_KingLT"
   Target_en_us "Insert King LT"
   Target_de_de "Larynxtubus einsetzen"
   Target_zh_cn "插入King喉管"
   Modified 1730466163
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6311265606824A7E}" {
   Id "ACE_Medical-UserAction_NeedleDecompression"
   Target_en_us "Perform needle decompression"
   Target_de_de "Nadeldekompression durchführen"
   Target_zh_cn "進行胸腔穿刺減壓術"
   Modified 1730466210
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{64FF4A2320445A13}" {
   Id "ACE_Medical-UserAction_OxygenMask"
   Target_en_us "Put on oxygen mask"
   Target_de_de "Sauerstoffmaske anziehen"
   Target_zh_cn "戴上氧氣面罩"
   Modified 1730466243
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6719486DE90061BC}" {
   Id "ACE_Medical-UserAction_TiltHead"
   Target_en_us "Lift chin"
   Target_de_de "Kinn anheben"
   Target_zh_cn "抬下巴"
   Modified 1730466264
   Author "Kexanone"
   LastChanged "YuanYu"
  }
 }
}
