StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64FF4A203D8FE526}" {
   Id "ACE_Medical-InfoWidget_ChestSeal"
   Target_en_us "Prevents tension pneumothorax"
   Target_de_de "Verhindert die Bildung einer Spannungspneumothorax"
   Modified 1694634449
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3A2AFEA00}" {
   Id "ACE_Medical-InfoWidget_KingLT"
   Target_en_us "Prevents obstruction and occlusion of airways"
   Target_de_de "Verhindert Obstruktion und Okklusion der Atemwege"
   Modified 1658280043
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A2623C65D0D}" {
   Id "ACE_Medical-InfoWidget_NCDKit"
   Target_en_us "Used for treating tension pneumothorax"
   Target_de_de "Zum Behandeln von Spannungspneumothorax"
   Modified 1694634480
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A23ED61E92B}" {
   Id "ACE_Medical-InfoWidget_OxygenMask"
   Target_en_us "Provides supplemental oxygen"
   Target_de_de "Sauerstoff zuführen"
   Modified 1700362805
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A20D0C03B3A}" {
   Id "ACE_Medical-Item_ChestSeal_Description"
   Target_en_us "Special dressing for open chest wounds"
   Target_de_de "Spezialverband für offenen Brustkorbverletzungen"
   Modified 1694633389
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A20DDF8616D}" {
   Id "ACE_Medical-Item_ChestSeal_Name"
   Target_en_us "Chest Seal"
   Target_de_de "Thorax Pflaster"
   Modified 1694633304
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3AABB4BEF}" {
   Id "ACE_Medical-Item_KingLT_Description"
   Target_en_us "Airway management device inserted into throat"
   Target_de_de "Hilfsmittel zur Atemwegssicherung"
   Modified 1658286267
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F3B0E7DA62}" {
   Id "ACE_Medical-Item_KingLT_Name"
   Target_en_us "King LT"
   Target_de_de "Larynxtubus"
   Modified 1658279424
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A2633C94C03}" {
   Id "ACE_Medical-Item_NCDKit_Description"
   Target_en_us "Kit for performing needle decompression"
   Target_de_de "Set zur Durchführung von Nadeldekompression"
   Modified 1694634678
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A263E864FA9}" {
   Id "ACE_Medical-Item_NCDKit_Name"
   Target_en_us "NCD Kit"
   Target_de_de "Dekompressionsnadelset"
   Modified 1694634641
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A23362FB915}" {
   Id "ACE_Medical-Item_OxygenMask_Description"
   Target_en_us "Mask for oxygen therapy"
   Target_de_de "Maske für Sauerstofftherapie"
   Modified 1694633716
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A2335B51A2F}" {
   Id "ACE_Medical-Item_OxygenMask_Name"
   Target_en_us "Oxygen Mask"
   Target_de_de "Sauerstoffmaske"
   Modified 1694633611
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{671625C94FF978B0}" {
   Id "ACE_Medical-Notification_BREATHING_RESULT"
   Target_en_us "You find a respiratory rate of %1 breaths per minute"
   Target_de_de "Die Atemfrequenz ist %1 AZ/min"
   Modified 1729515075
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754FA15390F40}" {
   Id "ACE_Medical-Notification_SPO2_RESULT"
   Target_en_us "You find a SpO2 of %1%"
   Target_de_de " SpO2 ist %1%"
   Modified 1658284253
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{671D563325641152}" {
   Id "ACE_Medical-Pneumothorax"
   Target_en_us "Pneumothorax"
   Target_de_de "Pneumothorax"
   Modified 1729978799
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6559386744A11E53}" {
   Id "ACE_Medical-RadialMenu_AirwayThoraxManagement"
   Target_en_us "Airway/Thorax management"
   Target_de_de "Atemweg/Brustkorb Versorgung"
   Modified 1700362756
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{671D5633273D3233}" {
   Id "ACE_Medical-TensionPneumothorax"
   Target_en_us "Tension pneumothorax"
   Target_de_de "Spannungspneumothorax"
   Modified 1729978791
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{671625C89F878900}" {
   Id "ACE_Medical-UserAction_CheckBreathing"
   Target_en_us "Check respiratory rate"
   Target_de_de "Atemfrequenz überprüfen"
   Modified 1729514646
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62D754F96369C7F7}" {
   Id "ACE_Medical-UserAction_CheckSpO2"
   Target_en_us "Check SpO2"
   Target_de_de "SpO2 bestimmen"
   Modified 1658284451
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{63112656052CFC80}" {
   Id "ACE_Medical-UserAction_ChestSeal"
   Target_en_us "Use chest seal"
   Target_de_de "Thorax Pflaster anwenden"
   Modified 1662077541
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6719486F0C433459}" {
   Id "ACE_Medical-UserAction_ClearVomit"
   Target_en_us "Clear vomit"
   Target_de_de "Erbrochenes entfernen"
   Modified 1729713671
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6311265639790D08}" {
   Id "ACE_Medical-UserAction_KingLT"
   Target_en_us "Insert King LT"
   Target_de_de "Larynxtubus einsetzen"
   Modified 1662077451
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6311265606824A7E}" {
   Id "ACE_Medical-UserAction_NeedleDecompression"
   Target_en_us "Perform needle decompression"
   Target_de_de "Nadeldekompression durchführen"
   Modified 1662077408
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{64FF4A2320445A13}" {
   Id "ACE_Medical-UserAction_OxygenMask"
   Target_en_us "Put on oxygen mask"
   Target_de_de "Sauerstoffmaske anziehen"
   Modified 1694632641
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6719486DE90061BC}" {
   Id "ACE_Medical-UserAction_TiltHead"
   Target_en_us "Lift chin"
   Target_de_de "Kinn anheben"
   Modified 1729712783
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}