ACE_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69D0C6193EA5B0A5}" {
   m_sEntityPrefab "{3C86938A05C83673}Prefabs/Items/Equipment/Patches/ACE_AnvilPatch_RHS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69D0C6193EA5B00F}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{69D140B6B99EA6B7}" {
   m_sEntityPrefab "{B4448714EFB83E46}Prefabs/Items/Equipment/Patches/ACE_MedicPatch_RHS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69D140B6B99EA628}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}