SCR_NotificationConfig {
 m_aNotificationDisplayData {
  SCR_NotificationDisplayData "{6856039A1C33B592}" {
   m_NotificationKey ACE_MEDICAL_DEFIBRILLATION_CONNECTED
   m_bPriorityNotification 1
   m_bAddFriendlyIndicator 1
   m_info SCR_UINotificationInfo "{6856039A07BA1E95}" {
    Name "#ACE-MedicalDefibrillation_Notification_PatientConnected"
    Icon "{B9199157B90D6216}UI/Textures/InventoryIcons/Medical/Medical-icons.imageset"
    IconSetName "Unconscious_UI"
    m_cNotificationColor POSITIVE
   }
  }
  SCR_NotificationDisplayData "{68575088086B55F9}" {
   m_NotificationKey ACE_MEDICAL_DEFIBRILLATION_DISCONNECTED
   m_bPriorityNotification 1
   m_bAddFriendlyIndicator 1
   m_info SCR_UINotificationInfo "{68575088086B997E}" {
    Name "#ACE-MedicalDefibrillation_Notification_PatientDisconnected"
    Icon "{B9199157B90D6216}UI/Textures/InventoryIcons/Medical/Medical-icons.imageset"
    IconSetName "Unconscious_UI"
    m_cNotificationColor WARNING
   }
  }
  SCR_NotificationDisplayData "{6857508A198CF214}" {
   m_NotificationKey ACE_MEDICAL_DEFIBRILLATION_SHOCKDELIVERED
   m_bPriorityNotification 1
   m_bAddFriendlyIndicator 1
   m_info SCR_UINotificationInfo "{6857508A198CF251}" {
    Name "#ACE-MedicalDefibrillation_Notification_ShockDelivered"
    Icon "{B9199157B90D6216}UI/Textures/InventoryIcons/Medical/Medical-icons.imageset"
    IconSetName "Unconscious_UI"
    m_cNotificationColor NEGATIVE
   }
  }
  SCR_NotificationDisplayData "{6857508ACA4A84D2}" {
   m_NotificationKey ACE_MEDICAL_DEFIBRILLATION_UNABLETOCONNECT
   m_bPriorityNotification 1
   m_bAddFriendlyIndicator 1
   m_info SCR_UINotificationInfo "{6857508ACA4A850B}" {
    Name "#ACE-MedicalDefibrillation_Notification_UnableToConnectPatient"
    Icon "{B9199157B90D6216}UI/Textures/InventoryIcons/Medical/Medical-icons.imageset"
    IconSetName "Unconscious_UI"
    m_cNotificationColor WARNING
   }
  }
 }
}