SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{B9ADA89641AE25E3}PrefabsEditable/EffectsModules/Mortar/Smoke/ACE_EffectModule_MortarShell_ChokingAgent.et"
  "{E7FCD07D7A78DEA2}PrefabsEditable/EffectsModules/Mortar/Smoke/ACE_EffectModule_MortarShell_Sarin.et"
  "{8185136DC0564064}Prefabs/Systems/DamageAreas/E_ACE_DamageArea_ChokingAgent.et"
 }
}