StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68F762272F79489D}" {
   Id "ACE_Ballistics-Item_BallisticTables_Mrads_Description"
   Target_en_us "Collection of ballistic tables in milliradians for bullets compatible with your rifle."
   Target_de_de "Sammlung von Schusstafeln in Milliradians für Kugeln, die kompatibel sind mit deiner Waffe."
   Target_ko_kr "사용 중인 총에 맞는 탄환의 밀리라디안(Mil) 단위 탄도표입니다."
   Target_zh_cn "收集與您步槍相容子彈之密位 (mrad) 彈道數據表"
   Modified 1769403357
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{68F7622720A91AF2}" {
   Id "ACE_Ballistics-Item_BallisticTables_Mrads_Name"
   Target_en_us "Ballistic Tables in mrads"
   Target_de_de "Schusstafeln in mrads"
   Target_ko_kr "탄도표 (Mil 단위)"
   Target_zh_cn "mrad 密位彈道表"
   Modified 1769403386
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{68F76227713095DD}" {
   Id "ACE_Ballistics-Item_BallisticTables_WpMils_Description"
   Target_en_us "Collection of ballistic tables in Warsaw Pact mils for bullets compatible with your rifle."
   Target_de_de "Sammlung von Schusstafeln in Warschauer Pakt mils für Kugeln, die kompatibel sind mit deiner Waffe."
   Target_ko_kr "사용 중인 총에 맞는 탄환의 바르샤바 조약기구 규격의 밀리라디안(WP Mil) 단위 탄도표입니다."
   Target_zh_cn "收集與您步槍相容子彈之華沙公約密位彈道數據表"
   Modified 1769403437
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{68F7622774AC7852}" {
   Id "ACE_Ballistics-Item_BallisticTables_WpMils_Name"
   Target_en_us "Ballistic Tables in WP mils"
   Target_de_de "Schusstafeln in WP mils"
   Target_ko_kr "탄도표 (WP Mil 단위)"
   Target_zh_cn "華約密位彈道表"
   Modified 1769403497
   Author "Kexanone"
   LastChanged "YuanYu"
  }
 }
}
