StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68F762272F79489D}" {
   Id "ACE_Ballistics-Item_BallisticTables_US_Description"
   Target_en_us "Collection of ballistic tables in milliradians for bullets compatible with your rifle."
   Modified 1761045239
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{68F7622720A91AF2}" {
   Id "ACE_Ballistics-Item_BallisticTables_US_Name"
   Target_en_us "US Ballistic Tables"
   Modified 1761044909
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{68F76227713095DD}" {
   Id "ACE_Ballistics-Item_BallisticTables_USSR_Description"
   Target_en_us "Collection of ballistic tables in Warsaw Pact mils for bullets compatible with your rifle."
   Modified 1761045228
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{68F7622774AC7852}" {
   Id "ACE_Ballistics-Item_BallisticTables_USSR_Name"
   Target_en_us "USSR Ballistic Tables"
   Modified 1761044912
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}