SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F7414CA4A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69B604856740FFD2}" {
     m_sEntityPrefab "{3DD5351CFB98FC7F}Prefabs/Items/Equipment/MineDetector/ACE_MineDetector_VMM3.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69B419EA8D15FDCE}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD5F1351A624}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69BB0467A2A08833}" {
     m_sEntityPrefab "{619F4A05EE0F4105}Prefabs/Items/Equipment/Detonators/ACE_DeadManSwitch.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BB0467A2A08B88}" {
       m_eItemType EXPLOSIVES
       m_iSupplyCost 15
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}