StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{644826487CAE8882}" {
   Id "ACE_Radio-Settings-Radio"
   Target_en_us "Radio"
   Target_pl_pl "Radio"
   Modified 1682450666
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264807CE1461}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch1"
   Target_en_us "Ch.1 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 1"
   Modified 1682450683
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264808F0EDBE}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch2"
   Target_en_us "Ch.2 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 2"
   Modified 1682450690
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{644826481FB40F2F}" {
   Id "ACE_Radio-Settings-Radio_Beep_High"
   Target_en_us "High"
   Target_pl_pl "Wysoki"
   Modified 1682450695
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264811A5CBD7}" {
   Id "ACE_Radio-Settings-Radio_Beep_Low"
   Target_en_us "Low"
   Target_pl_pl "Niski"
   Modified 1682450698
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{644826480D886913}" {
   Id "ACE_Radio-Settings-Radio_Beep_Off"
   Target_en_us "Off"
   Target_pl_pl "Wyłączony"
   Modified 1682450701
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{64482648D1C29B76}" {
   Id "ACE_Radio-Settings_Beep_Cycle"
   Target_en_us "Transceiver cycle beep"
   Target_pl_pl "Pisk przy zmianie nadajnika"
   Modified 1682450920
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{664EB3C5389562D0}" {
   Id "ACE_Radio-Settings_Click_Off"
   Target_en_us "Click-off sound when transmission ends"
   Target_pl_pl "Dźwięk odłączenia przy zakończeniu transmisji"
   Modified 1716434296
   Author "darkshifty"
   LastChanged "darkshifty"
  }
 }
}
