StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{66CF3B5DD2400B3F}" {
   Id "ACE_Radio-FailReason_NotLoaded"
   Target_en_us "Not loaded"
   Target_de_de "Nicht geladen"
   Modified 1724863097
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66657BEC7C58D254}" {
   Id "ACE_Radio-Item_KYK13_Description"
   Target_en_us "A module used for transferring crypographic keys to radios."
   Target_de_de "Ein Modul zum Übetragen von kryptographischen Schlüsseln auf Funkgeräte."
   Modified 1717962704
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66657BEC7B8734FC}" {
   Id "ACE_Radio-Item_KYK13_Name"
   Target_en_us "KYK-13 Fill Device"
   Modified 1717961004
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{644826487CAE8882}" {
   Id "ACE_Radio-Settings-Radio"
   Target_en_us "Radio"
   Target_pl_pl "Radio"
   Modified 1682450666
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264807CE1461}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch1"
   Target_en_us "Ch.1 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 1"
   Modified 1682450683
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264808F0EDBE}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch2"
   Target_en_us "Ch.2 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 2"
   Modified 1682450690
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{644826481FB40F2F}" {
   Id "ACE_Radio-Settings-Radio_Beep_High"
   Target_en_us "High"
   Target_pl_pl "Wysoki"
   Modified 1682450695
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{6448264811A5CBD7}" {
   Id "ACE_Radio-Settings-Radio_Beep_Low"
   Target_en_us "Low"
   Target_pl_pl "Niski"
   Modified 1682450698
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{644826480D886913}" {
   Id "ACE_Radio-Settings-Radio_Beep_Off"
   Target_en_us "Off"
   Target_pl_pl "Wyłączony"
   Modified 1682450701
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{64482648D1C29B76}" {
   Id "ACE_Radio-Settings_Beep_Cycle"
   Target_en_us "Transceiver cycle beep"
   Target_pl_pl "Pisk przy zmianie nadajnika"
   Modified 1682450920
   Author "veteran29"
   LastChanged "veteran29"
  }
  CustomStringTableItem "{66CF3B5A5C85AB29}" {
   Id "ACE_Radio-UserAction_Address"
   Target_en_us "Address: %1"
   Target_de_de "Adresse: %1"
   Modified 1724863571
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66CF3B5BAABA47AE}" {
   Id "ACE_Radio-UserAction_ClearAll"
   Target_en_us "Clear all"
   Target_de_de "Alle löschen"
   Modified 1724863735
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66CF3B5D07D15121}" {
   Id "ACE_Radio-UserAction_CopyKey"
   Target_en_us "Copy %1 to %2"
   Target_de_de "Kopiere %1 nach %2"
   Modified 1724863181
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{66CF3B5D60010DC8}" {
   Id "ACE_Radio-UserAction_LoadKey"
   Target_en_us "Load %1"
   Target_de_de "Lade %1"
   Modified 1724863191
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}