StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{66CF3B5DD2400B3F}" {
   Id "ACE_Radio-FailReason_NotLoaded"
   Target_en_us "Not loaded"
   Target_de_de "Nicht geladen"
   Target_zh_cn "尚未載入"
   Modified 1730462291
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66657BEC7C58D254}" {
   Id "ACE_Radio-Item_KYK13_Description"
   Target_en_us "A module used for transferring cryptographic keys to radios."
   Target_de_de "Ein Modul zum Übetragen von kryptographischen Schlüsseln auf Funkgeräte."
   Target_zh_cn "用於向無線電設備傳輸加密金鑰的模組"
   Modified 1730462250
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66657BEC7B8734FC}" {
   Id "ACE_Radio-Item_KYK13_Name"
   Target_en_us "KYK-13 Fill Device"
   Target_zh_cn "KYK-13 加密金鑰加載器"
   Modified 1730462791
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{644826487CAE8882}" {
   Id "ACE_Radio-Settings-Radio"
   Target_en_us "Radio"
   Target_pl_pl "Radio"
   Target_zh_cn "無線電"
   Target_ko_kr "무전기"
   Modified 1725493460
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{6448264807CE1461}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch1"
   Target_en_us "Ch.1 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 1"
   Target_zh_cn "Ch.1 傳輸蜂鳴聲"
   Target_ko_kr "1 채널 송신음"
   Modified 1725493513
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{6448264808F0EDBE}" {
   Id "ACE_Radio-Settings-Radio_Beep_Ch2"
   Target_en_us "Ch.2 transmission beep"
   Target_pl_pl "Pisk transmisji kanału 2"
   Target_zh_cn "Ch.2 傳輸蜂鳴聲"
   Target_ko_kr "2 채널 송신음"
   Modified 1725493517
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{644826481FB40F2F}" {
   Id "ACE_Radio-Settings-Radio_Beep_High"
   Target_en_us "High"
   Target_pl_pl "Wysoki"
   Target_zh_cn "高音"
   Target_ko_kr "높음"
   Modified 1725492506
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{6448264811A5CBD7}" {
   Id "ACE_Radio-Settings-Radio_Beep_Low"
   Target_en_us "Low"
   Target_pl_pl "Niski"
   Target_zh_cn "低音"
   Target_ko_kr "낮음"
   Modified 1725492514
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{644826480D886913}" {
   Id "ACE_Radio-Settings-Radio_Beep_Off"
   Target_en_us "Off"
   Target_pl_pl "Wyłączony"
   Target_zh_cn "關閉"
   Target_ko_kr "없음"
   Modified 1725492519
   Author "veteran29"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64482648D1C29B76}" {
   Id "ACE_Radio-Settings_Beep_Cycle"
   Target_en_us "Transceiver cycle beep"
   Target_pl_pl "Pisk przy zmianie nadajnika"
   Target_zh_cn "頻道切換蜂鳴聲"
   Target_ko_kr "무전기 순환음"
   Modified 1725493711
   Author "veteran29"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{664EB3C5389562D0}" {
   Id "ACE_Radio-Settings_Click_Off"
   Target_en_us "Click-off sound when transmission ends"
   Target_pl_pl "Dźwięk odłączenia przy zakończeniu transmisji"
   Target_zh_cn "傳輸結束時的斷訊提示音"
   Modified 1730462812
   Author "darkshifty"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66CF3B5A5C85AB29}" {
   Id "ACE_Radio-UserAction_Address"
   Target_en_us "Address: %1"
   Target_de_de "Adresse: %1"
   Target_zh_cn "位址： %1"
   Modified 1730462941
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66CF3B5BAABA47AE}" {
   Id "ACE_Radio-UserAction_ClearAll"
   Target_en_us "Clear all"
   Target_de_de "Alle löschen"
   Target_zh_cn "全部清除"
   Modified 1730463063
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66CF3B5D07D15121}" {
   Id "ACE_Radio-UserAction_CopyKey"
   Target_en_us "Copy %1 to %2"
   Target_de_de "Kopiere %1 nach %2"
   Target_zh_cn "將 %1 複製到 %2"
   Modified 1730463110
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{66CF3B5D60010DC8}" {
   Id "ACE_Radio-UserAction_LoadKey"
   Target_en_us "Load %1"
   Target_de_de "Lade %1"
   Target_zh_cn "讀取 %1"
   Modified 1730462989
   Author "Kexanone"
   LastChanged "YuanYu"
  }
 }
}
