SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216210}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216273}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216255}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{651100784354DF07}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D216247}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D2162AA}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{5D4A87E86D21628F}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D13C72A54D06B0}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D218DEDB095B36}" : "{382ACD2D23811DDE}Configs/EntityCatalog/USSR/ACE_InventoryItems_EntityCatalog_Equipment_USSR.conf" {
  }
 }
}