SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453BCB39DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{697F3554EBBBEACE}" {
     m_sEntityPrefab "{F690896CF54DE691}Prefabs/Items/Medicine/Heatpack/ACE_Medical_Heatpack.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{697F3554DBB2331B}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69B32196B21C654E}" {
     m_sEntityPrefab "{0DB1B1E5F129A3E2}Prefabs/Items/Medicine/OxygenMask/ACE_Medical_SafetyBlanket.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69B32196B21C6402}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}