StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62F97CC0ADB17508}" {
   Id "ACE_Doors-UserAction_Adjust"
   Target_en_us "Adjust"
   Target_fr_fr "Ajuster"
   Target_it_it "Regolare"
   Target_de_de "Anpassen"
   Target_es_es "Ajustar"
   Target_cs_cz "Upravit"
   Target_pl_pl "Dostosować"
   Target_ru_ru "Настроить"
   Target_ja_jp "調整する"
   Target_ko_kr "조정하다"
   Target_pt_br "Ajustar"
   Target_zh_cn "调整"
   Target_uk_ua "Налаштувати"
   Modified 1700853720
   Author "Gray"
   LastChanged "Gray"
  }
 }
}