StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64A40CB0E1FB16B7}" {
   Id "ACE_TacticalPeriscope-Item_Periscope_Description"
   Target_en_us "Handheld periscope for peaking from behind cover."
   Target_de_de "Handgetragenes Periskop um über Hindernisse zu schauen."
   Target_zh_cn "可在掩體後方觀察用的手持式潛望鏡"
   Target_ko_kr "엄폐물 뒤에서 엿볼 수 있는 휴대용 잠망경입니다."
   Modified 1725496689
   Author "Kex"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{64A40CB0E2D412E0}" {
   Id "ACE_TacticalPeriscope-Item_Periscope_Name"
   Target_en_us "Periscope"
   Target_de_de "Periskop"
   Target_zh_cn "戰術潛望鏡"
   Target_ko_kr "잠망경"
   Modified 1725496708
   Author "Kex"
   LastChanged "Psycool"
  }
 }
}
