StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64A40CB0E1FB16B7}" {
   Id "ACE_TacticalPeriscope-Item_Periscope_Description"
   Target_en_us "Handheld periscope for peaking from behind cover."
   Target_de_de "Handgetragenes Periskop um über Hindernisse zu schauen."
   Modified 1688483864
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{64A40CB0E2D412E0}" {
   Id "ACE_TacticalPeriscope-Item_Periscope_Name"
   Target_en_us "Periscope"
   Target_de_de "Periskop"
   Modified 1688483365
   Author "Kex"
   LastChanged "Kex"
  }
 }
}