StringTableRuntime {
 Ids {
  "ACE_Medical-Heatpack-Description"
  "ACE_Medical-Heatpack-Name"
  "ACE_Medical-InfoWidget-Heatpack"
  "ACE_Medical-Notification_TEMPERATURE_RESULT"
  "ACE_Medical-UserAction_CheckTemperature"
 }
 Texts {
  "Administered to patients with hypothermia."
  "Instant Hot Pack"
  "Increases core temperature"
  "Core temperature is %1 °C"
  "Check temperature"
 }
}