StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{6982160C1238488B}" {
   Id "ACE_Medical-Heatpack-Description"
   Target_en_us "Administered to patients with hypothermia."
  }
  DefaultStringTableItem "{6982160C276534CC}" {
   Id "ACE_Medical-Heatpack-Name"
   Target_en_us "Instant Hot Pack"
  }
  DefaultStringTableItem "{6982160C0C8D9F2B}" {
   Id "ACE_Medical-InfoWidget-Heatpack"
   Target_en_us "Increases core temperature"
  }
  DefaultStringTableItem "{697B73666761BDF2}" {
   Id "ACE_Medical-Notification_TEMPERATURE_RESULT"
   Target_en_us "Core temperature is %1 °C"
  }
  DefaultStringTableItem "{697B7433C217BB6B}" {
   Id "ACE_Medical-UserAction_CheckTemperature"
   Target_en_us "Check temperature"
  }
 }
}