SCR_NotificationConfig {
 m_aNotificationDisplayData {
  SCR_NotificationNumber "{697B6862AF43F71F}" {
   m_NotificationKey ACE_MEDICAL_TEMPERATURE_RESULT
   m_info SCR_UINotificationInfo "{697B6862A9D51B55}" {
    Name "#ACE_Medical-Notification_TEMPERATURE_RESULT"
    m_cNotificationColor WARNING
   }
  }
 }
}