StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68FC0664618BD07D}" {
   Id "ACE_Scopes-AddonName"
   Target_en_us "Scopes"
   Target_de_de "Zielfernrohre"
   Target_ko_kr "조준경"
   Modified 1761348539
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{68FC0667C6ED8F01}" {
   Id "ACE_Scopes-KeyBind_ACE_HorizontalZeroingLeft_Name"
   Target_en_us "Adjust windage left"
   Target_de_de "Seite nach links korrigieren"
   Target_ko_kr "왼쪽으로 영점 조정"
   Modified 1761349035
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{68FC0667C09FF0EF}" {
   Id "ACE_Scopes-KeyBind_ACE_HorizontalZeroingRight_Name"
   Target_en_us "Adjust windage right"
   Target_de_de "Seite nach rechts korrigieren"
   Target_ko_kr "오른쪽으로 영점 조정"
   Modified 1761349040
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{68FC0667CA80F035}" {
   Id "ACE_Scopes-KeyBind_VerticalZeroingDown_Name"
   Target_en_us "Adjust elevation down"
   Target_de_de "Höhe nach unten korrigieren"
   Target_ko_kr "아래로 영점 조정"
   Modified 1761349002
   Author "Kexanone"
   LastChanged "Psycool"
  }
  CustomStringTableItem "{68FC0667D7F52473}" {
   Id "ACE_Scopes-KeyBind_VerticalZeroingUp_Name"
   Target_en_us "Adjust elevation up "
   Target_de_de "Höhe nach oben korrigieren"
   Target_ko_kr "위로 영점 조정"
   Modified 1761348994
   Author "Kexanone"
   LastChanged "Psycool"
  }
 }
}