SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C9744F2}" {
   m_iACE_Priority -70
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C9744D1}" {
   m_iACE_Priority -60
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C974435}" {
   m_iACE_Priority -50
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C97443B}" {
   m_iACE_Priority -40
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C974413}" {
   m_iACE_Priority -30
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C974408}" {
   m_iACE_Priority -20
  }
  SCR_EntityCatalogMultiListEntry "{5D4A8E6F2C97447C}" {
   m_iACE_Priority -10
  }
  ACE_EntityCatalogMultiListEntry "{69D13C72BD84FE8B}" : "{A5E3827C546B8210}Configs/EntityCatalog/ACE_InventoryItems_EntityCatalog_Medical.conf" {
  }
  ACE_EntityCatalogMultiListEntry "{69D218DEB1B25736}" : "{12790B4E7D42F952}Configs/EntityCatalog/US/ACE_InventoryItems_EntityCatalog_Equipment_US.conf" {
  }
 }
}