SCR_EntityCatalogMultiList {
 m_aMultiLists {
  ACE_EntityCatalogMultiListEntry "{69D102AC05BFC4DC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69DE154744A3CB83}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{69E224A9CD02DCC4}" {
     m_bEnabled 0
    }
   }
  }
 }
}