StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6228B55EF02EBEDA}" {
   Id "ACE_Medical-AmmoniumCarbonatePackageAction"
   Target_en_us "Hold under nose"
   Target_de_de "Unter die Nase halten"
   Target_ru_ru "Поднести к носу"
   Target_ja_jp "鼻の下に当てる"
   Target_ko_kr "코 아래에 대기"
   Target_pt_br "Segure sob o nariz"
   Target_zh_cn "置於鼻下"
   Target_uk_ua "Піднести до носа"
   Modified 1787874444
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B53ACDD034A6}" {
   Id "ACE_Medical-BloodState_Class1"
   Target_en_us "Class I hemorrhage"
   Target_de_de "Blutung Klasse 1"
   Target_ru_ru "Кровопотеря I класса"
   Target_ja_jp "I度出血"
   Target_ko_kr "경미한 실혈 (1급)"
   Target_pt_br "Hemorragia de Classe I"
   Target_zh_cn "I 級出血"
   Target_uk_ua "Кровотеча I ступеня"
   Modified 1787875502
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B53AC27D464E}" {
   Id "ACE_Medical-BloodState_Class2"
   Target_en_us "Class II hemorrhage"
   Target_de_de "Blutung Klasse 2"
   Target_ru_ru "Кровопотеря II класса"
   Target_ja_jp "II度出血"
   Target_ko_kr "보통 실혈 (2급)"
   Target_pt_br "Hemorragia de Classe II"
   Target_zh_cn "II 級出血"
   Target_uk_ua "Кровотеча II ступеня"
   Modified 1787875505
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B53AC01F5452}" {
   Id "ACE_Medical-BloodState_Class3"
   Target_en_us "Class III hemorrhage"
   Target_de_de "Blutung Klasse 3"
   Target_ru_ru "Кровопотеря III класса"
   Target_ja_jp "III度出血"
   Target_ko_kr "심한 실혈 (3급)"
   Target_pt_br "Hemorragia de Classe III"
   Target_zh_cn "III 級出血"
   Target_uk_ua "Кровотеча III ступеня"
   Modified 1787875510
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B53AC6AA6AB1}" {
   Id "ACE_Medical-BloodState_Class4"
   Target_en_us "Class IV hemorrhage"
   Target_de_de "Blutung Klasse 4"
   Target_ru_ru "Кровопотеря IV класса"
   Target_ja_jp "IV度出血"
   Target_ko_kr "극심한 실혈 (4급)"
   Target_pt_br "Hemorragia de Classe IV"
   Target_zh_cn "IV 級出血"
   Target_uk_ua "Кровотеча IV ступеня"
   Modified 1787875513
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55046CF7CC7}" {
   Id "ACE_Medical-CheckBloodPressureAction"
   Target_en_us "Check blood pressure"
   Target_de_de "Blutdruck überprüfen"
   Target_ru_ru "Проверить давление"
   Target_ja_jp "血圧を測る"
   Target_ko_kr "혈압 확인하기"
   Target_pt_br "Verificar pressão arterial"
   Target_zh_cn "量測血壓"
   Target_uk_ua "Перевірити тиск"
   Modified 1787874554
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5504DC3E45E}" {
   Id "ACE_Medical-CheckPulseAction"
   Target_en_us "Check pulse"
   Target_de_de "Puls überprüfen"
   Target_ru_ru "Проверить пульс"
   Target_ja_jp "脈拍を測る"
   Target_ko_kr "맥박 확인하기"
   Target_pt_br "Verificar pulso"
   Target_zh_cn "量測脈搏"
   Target_uk_ua "Перевірити пульс"
   Modified 1787874561
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5503F479D0C}" {
   Id "ACE_Medical-CPRAction"
   Target_en_us "Perform CPR"
   Target_de_de "CPR durchführen"
   Target_ru_ru "Выполнить СЛР"
   Target_ja_jp "心肺蘇生を行う"
   Target_ko_kr "심폐소생술 수행"
   Target_pt_br "Realizar RCP"
   Target_zh_cn "進行心肺復甦術 (CPR)"
   Target_uk_ua "Провести серцево-легеневу реанімацію"
   Modified 1787874506
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6624FDAA28CE989A}" {
   Id "ACE_Medical-Editor_TooltipDetail_Brain_Name"
   Target_en_us "Brain"
   Target_de_de "Gehirn"
   Target_ru_ru "Мозг"
   Target_ja_jp "脳"
   Target_ko_kr "뇌"
   Target_zh_cn "大腦"
   Modified 1787874576
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6230E5C2DA63508A}" {
   Id "ACE_Medical-Editor_TooltipDetail_VitalSigns_Name"
   Target_en_us "Vital signs"
   Target_de_de "Vitaldaten"
   Target_ru_ru "Жизненные показатели"
   Target_ja_jp "バイタルサイン"
   Target_ko_kr "바이탈 사인"
   Target_zh_cn "生命徵象"
   Target_uk_ua "Життєві показники"
   Modified 1787874581
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6720C07189EC3236}" {
   Id "ACE_Medical-FailReason_NotOnBack"
   Target_en_us "Not on back"
   Target_de_de "Nicht auf dem Rücken"
   Target_ja_jp "仰向けではありません"
   Target_ko_kr "똑바로 눕혀지지 않음"
   Modified 1787874599
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55BAA8F501D}" {
   Id "ACE_Medical-InfoWidget_AmmoniumCarbonate"
   Target_en_us "Increases wake-up chance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_ru_ru "Повышает  вероятность пробуждения"
   Target_ja_jp "覚醒の可能性を高める"
   Target_ko_kr "환자가 깨어날 확률 증가"
   Target_pt_br "Aumenta a chance de acordar"
   Target_zh_cn "增加甦醒機率"
   Target_uk_ua "Збільшує шанс отямлення"
   Modified 1787874636
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55BAE36450B}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases heart rate"
   Target_de_de "Erhöht die Herzfrequenz"
   Target_ru_ru "Увеличивает частоту пульса"
   Target_ja_jp "心拍数を上げる"
   Target_ko_kr "심박수 증가"
   Target_pt_br "Aumenta a frequência cardíaca"
   Target_zh_cn "提高心率"
   Target_uk_ua "Підвищує частоту серцевих скорочень"
   Modified 1787874646
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55BA0A3E335}" {
   Id "ACE_Medical-InfoWidget_Metoprolol"
   Target_en_us "Decreases heart rate"
   Target_de_de "Sinkt die Herzfrequenz"
   Target_ru_ru "Снижает частоту пульса"
   Target_ja_jp "心拍数を下げる"
   Target_ko_kr "심박수 감소"
   Target_pt_br "Reduz a frequência cardíaca"
   Target_zh_cn "降低心率"
   Target_uk_ua "Знижує частоту серцевих скорочень"
   Modified 1787874662
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55BA77C7538}" {
   Id "ACE_Medical-InfoWidget_Naloxone"
   Target_en_us "Antagonist for opioids like morphine"
   Target_de_de "Antagonist für Opioide wie Morphin"
   Target_ru_ru "Блокатор опиоидов (например, морфина)"
   Target_ja_jp "モルヒネなどのオピオイド中毒を治療する"
   Target_ko_kr "모르핀 같은 오이포이드 계열 약물 중독을 치료"
   Target_pt_br "Antagonista para opioides como morfina"
   Target_zh_cn "對嗎啡等鴉片類藥物的拮抗劑"
   Target_uk_ua "Застосовується при передозуванні"
   Modified 1787874690
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55BB2295B31}" {
   Id "ACE_Medical-InfoWidget_Phenylephrine"
   Target_en_us "Increases blood pressure and slows down bleeding and transfusion"
   Target_de_de "Erhöht den Blutdrucks und verlangsamt Blutung und Transfusion"
   Target_ru_ru "Повышает давление и замедляет кровотечение и потребность в переливании"
   Target_ja_jp "血圧を上げ、出血および輸血を遅らせる"
   Target_ko_kr "혈압을 증가시키고 출혈과 수혈 속도를 늦춤"
   Target_pt_br "Aumenta a pressão arterial e diminui o sangramento e transfusão"
   Target_zh_cn "提高血壓，並減緩出血與輸血速度"
   Target_uk_ua "Підвищує артеріальний тиск"
   Modified 1787874736
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5586006E639}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Description"
   Target_en_us "Administered to unconscious patients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_ru_ru "Назначают пациентам без сознания."
   Target_ja_jp "意識不明の患者に投与する。"
   Target_ko_kr "의식불명의 환자에게 사용됩니다."
   Target_pt_br "Administrado a pacientes inconscientes."
   Target_zh_cn "給予無意識患者使用"
   Target_uk_ua "Застосовується до непритомних пацієнтів, УВАГА застосовувати при нормальних показниках ЧСС (близько 70 ударів на секунду) та Артеріальному тиску близько 120/80 "
   Modified 1787874799
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5586D87363C}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Name"
   Target_en_us "Ammonium Carbonate"
   Target_de_de "Ammoniumcarbonat"
   Target_ru_ru "Карбонат аммония"
   Target_ja_jp "炭酸アンモニウム"
   Target_ko_kr "탄산암모늄"
   Target_pt_br "Carbonato de Amônio"
   Target_zh_cn "碳酸铵 (嗅鹽)"
   Target_uk_ua "Амонію карбонат (нюхальна сіль)"
   Modified 1787874805
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55B9B65D93A}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to patients in cardiac arrest"
   Target_de_de "Verabreicht an Patienten mit Herzstillstand"
   Target_ru_ru "Назначают пациентам при остановке сердца"
   Target_ja_jp "心停止の患者に投与する。"
   Target_ko_kr "심정지 상태의 환자에게 투여됩니다."
   Target_pt_br "Administrado a pacientes em parada cardíaca"
   Target_zh_cn "給予心臟驟停的患者使用"
   Target_uk_ua "Застосовується при зупинці серця"
   Modified 1787874837
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{65C6FCD64D6EB190}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_de_de "Epinephrin"
   Target_ru_ru "Эпинефрин"
   Target_ja_jp "エピネフリン"
   Target_ko_kr "에피네프린"
   Target_zh_cn "腎上腺素"
   Target_uk_ua "Адреналін (Епінефрин)"
   Modified 1787874862
   Author "PC Ill"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5585D442A6C}" {
   Id "ACE_Medical-Item_Metoprolol_Description"
   Target_en_us "Administered to patients with too high heart rate"
   Target_de_de "Verabreicht an Patienten mit überhöhter Herzfrequenz"
   Target_ru_ru "Назначают пациентам при повышенном пульсе"
   Target_ja_jp "心拍数が過度に高い患者に投与する。"
   Target_ko_kr "심박수가 너무 높은 환자에게 투여됩니다."
   Target_pt_br "Administrado a pacientes com frequência cardíaca muito alta"
   Target_zh_cn "給予心率過高的患者使用"
   Target_uk_ua "Застосовується при занадто високому пульсі"
   Modified 1787874962
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5585EEF5D9C}" {
   Id "ACE_Medical-Item_Metoprolol_Name"
   Target_en_us "Metoprolol"
   Target_de_de "Metoprolol"
   Target_ru_ru "Метопролол"
   Target_ja_jp "メトプロロール"
   Target_ko_kr "메토프롤롤"
   Target_pt_br "Metoprolol"
   Target_zh_cn "美托洛爾 (Metoprolol)"
   Target_uk_ua "Метопролол"
   Modified 1787874979
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5582C95F2EA}" {
   Id "ACE_Medical-Item_Naloxone_Description"
   Target_en_us "Administered to patients with opioid overdose"
   Target_de_de "Verabreicht an Patienten mit Opioidüberdosis"
   Target_ru_ru "Назначают пациентам при передозировке опиойдами"
   Target_ja_jp "オピオイド過剰摂取の患者に投与する。"
   Target_ko_kr "오이포이드 계열 약물을 과다투여한 환자에게 사용됩니다."
   Target_pt_br "Administrado a pacientes com overdose de opioides"
   Target_zh_cn "給予鴉片類藥物過量的患者使用"
   Target_uk_ua "Застосовується при передозуванні опіоїдами"
   Modified 1787874994
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B558202D6005}" {
   Id "ACE_Medical-Item_Naloxone_Name"
   Target_en_us "Naloxone"
   Target_de_de "Naloxon"
   Target_ru_ru "Налоксон"
   Target_ja_jp "ナロキソン"
   Target_ko_kr "날록손"
   Target_pt_br "Naloxona"
   Target_zh_cn "納洛酮 (Naloxone)"
   Target_uk_ua "Налоксон"
   Modified 1787875009
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55877861E3A}" {
   Id "ACE_Medical-Item_Phenylephrine_Description"
   Target_en_us "Administered to patients for raising blood pressure"
   Target_de_de "Verabreicht an Patienten um den Blutdruck zu erhöhen"
   Target_ru_ru "Назначают пациентам при повышенном давлении"
   Target_ja_jp "血圧を上げる必要がある患者に投与する。"
   Target_ko_kr "환자의 혈압을 높이는 데 사용됩니다."
   Target_pt_br "Administrado a pacientes para elevar a pressão arterial"
   Target_zh_cn "給予因低血壓需要升壓的患者使用"
   Target_uk_ua "Застосовується для підвищення тиску"
   Modified 1787875032
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55875DE022F}" {
   Id "ACE_Medical-Item_Phenylephrine_Name"
   Target_en_us "Phenylephrine"
   Target_de_de "Phenylephrin"
   Target_ru_ru "Фенилэфрин"
   Target_ja_jp "フェニレフリン"
   Target_ko_kr "페닐에프린"
   Target_pt_br "Fenilefrina"
   Target_zh_cn "苯福林 (Phenylephrine)"
   Target_uk_ua "Фенілефрин"
   Modified 1787875345
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55ED01FBD98}" {
   Id "ACE_Medical-MetoprololInjectionAction"
   Target_en_us "Inject metoprolol"
   Target_de_de "Metoprolol injizieren"
   Target_ru_ru "Ввести метопролол"
   Target_ja_jp "メトプロロールを注射"
   Target_ko_kr "메토프롤롤 주사하기"
   Target_pt_br "Injetar metoprolol"
   Target_zh_cn "注射美托洛爾 (Metoprolol)"
   Target_uk_ua "Ввести метопролол"
   Modified 1787875353
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55ECF6624E9}" {
   Id "ACE_Medical-NaloxoneInjectionAction"
   Target_en_us "Inject naloxone"
   Target_de_de "Naloxon injizieren"
   Target_ru_ru "Ввести налоксон"
   Target_ja_jp "ナロキソンを注射"
   Target_ko_kr "날록손 주사하기"
   Target_pt_br "Injetar naloxona"
   Target_zh_cn "注射納洛酮 (Naloxone)"
   Target_uk_ua "Ввести налоксон"
   Modified 1787875367
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55235D38AF1}" {
   Id "ACE_Medical-Notification_BLOOD_PRESSURE_RESULT"
   Target_en_us "You find a blood pressure of %1/%2 mmHg"
   Target_de_de "Der Blutdruck liegt bei %1/%2 mmHg"
   Target_ru_ru "Давление у пациента %1/%2 мм рт.ст"
   Target_ja_jp "血圧は%1/%2 mmHgです"
   Target_ko_kr "혈압이 %1/%2mmHg임을 알아냈습니다"
   Target_pt_br "pressão arterial em %1/%2 mmHg"
   Target_zh_cn "你測得的血壓為 %1/%2 mmHg"
   Target_uk_ua "У пацієнта тиск %1/%2 мм рт.ст."
   Modified 1787875419
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B5523F76CF1E}" {
   Id "ACE_Medical-Notification_PULSE_RESULT"
   Target_en_us "You find a heart rate of %1"
   Target_de_de "Herzfrequenz ist %1"
   Target_ru_ru "Пульс у пациента %1"
   Target_ja_jp "心拍数は%1です"
   Target_ko_kr "심박수가 %1임을 알아냈습니다"
   Target_pt_br "Frequência cardíaca em %1"
   Target_zh_cn "你測得的心律為 %1"
   Target_uk_ua "У пацієнта пульс %1"
   Modified 1787875436
   Author "Kexanone"
   LastChanged "neruha"
  }
  CustomStringTableItem "{6228B55ED9DB4B14}" {
   Id "ACE_Medical-PhenylephrineInjectionAction"
   Target_en_us "Inject phenylephrine"
   Target_de_de "Phenylephrin injizieren"
   Target_ru_ru "Ввести фенилэфрин"
   Target_ja_jp "フェニレフリンを注射"
   Target_ko_kr "페닐에프린 주사하기"
   Target_pt_br "Injetar fenilefrina"
   Target_zh_cn "注射苯福林 (Phenylephrine)"
   Target_uk_ua "Ввести фенілефрин"
   Modified 1787875449
   Author "Kexanone"
   LastChanged "neruha"
  }
 }
}