StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6228B55EF02EBEDA}" {
   Id "ACE_Medical-AmmoniumCarbonatePackageAction"
   Target_en_us "Hold under nose"
   Target_de_de "Unter die Nase halten"
   Target_pt_br "Segure sob o nariz"
   Target_zh_cn "置於鼻下"
   Target_uk_ua "Піднести до носа"
   Modified 1725500839
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B53ACDD034A6}" {
   Id "ACE_Medical-BloodState_Class1"
   Target_en_us "Class I hemorrhage"
   Target_de_de "Blutung Klasse 1"
   Target_pt_br "Hemorragia de Classe I"
   Target_zh_cn "I 級出血"
   Target_uk_ua "Кровотеча I ступеня"
   Modified 1725499800
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B53AC27D464E}" {
   Id "ACE_Medical-BloodState_Class2"
   Target_en_us "Class II hemorrhage"
   Target_de_de "Blutung Klasse 2"
   Target_pt_br "Hemorragia de Classe II"
   Target_zh_cn "II 級出血"
   Target_uk_ua "Кровотеча II ступеня"
   Modified 1725499822
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B53AC01F5452}" {
   Id "ACE_Medical-BloodState_Class3"
   Target_en_us "Class III hemorrhage"
   Target_de_de "Blutung Klasse 3"
   Target_pt_br "Hemorragia de Classe III"
   Target_zh_cn "III 級出血"
   Target_uk_ua "Кровотеча III ступеня"
   Modified 1725499840
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B53AC6AA6AB1}" {
   Id "ACE_Medical-BloodState_Class4"
   Target_en_us "Class IV hemorrhage"
   Target_de_de "Blutung Klasse 4"
   Target_pt_br "Hemorragia de Classe IV"
   Target_zh_cn "IV 級出血"
   Target_uk_ua "Кровотеча IV ступеня"
   Modified 1725499846
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55046CF7CC7}" {
   Id "ACE_Medical-CheckBloodPressureAction"
   Target_en_us "Check blood pressure"
   Target_de_de "Blutdruck überprüfen"
   Target_pt_br "Verificar pressão arterial"
   Target_zh_cn "量測血壓"
   Target_uk_ua "Перевірити тиск"
   Modified 1725500513
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5504DC3E45E}" {
   Id "ACE_Medical-CheckPulseAction"
   Target_en_us "Check pulse"
   Target_de_de "Puls überprüfen"
   Target_pt_br "Verificar pulso"
   Target_zh_cn "量測脈搏"
   Target_uk_ua "Перевірити пульс"
   Modified 1725500537
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5503F479D0C}" {
   Id "ACE_Medical-CPRAction"
   Target_en_us "Perform CPR"
   Target_de_de "CPR durchführen"
   Target_pt_br "Realizar RCP"
   Target_zh_cn "進行心肺復甦術 (CPR)"
   Target_uk_ua "Провести серцево-легеневу реанімацію"
   Modified 1725500470
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6624FDAA28CE989A}" {
   Id "ACE_Medical-Editor_TooltipDetail_Brain_Name"
   Target_en_us "Brain"
   Target_de_de "Gehirn"
   Target_zh_cn "大腦"
   Modified 1725500425
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6230E5C2DA63508A}" {
   Id "ACE_Medical-Editor_TooltipDetail_VitalSigns_Name"
   Target_en_us "Vital signs"
   Target_de_de "Vitaldaten"
   Target_zh_cn "生命徵象"
   Target_uk_ua "Життєві показники"
   Modified 1725500626
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55BAA8F501D}" {
   Id "ACE_Medical-InfoWidget_AmmoniumCarbonate"
   Target_en_us "Increases wake-up chance"
   Target_de_de "Erhöht die Wahrscheinlichkeit des Aufwachens"
   Target_pt_br "Aumenta a chance de acordar"
   Target_zh_cn "增加甦醒機率"
   Target_uk_ua "Збільшує шанс отямлення"
   Modified 1725500657
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55BAE36450B}" {
   Id "ACE_Medical-InfoWidget_Epinephrine"
   Target_en_us "Increases heart rate"
   Target_de_de "Erhöht die Herzfrequenz"
   Target_pt_br "Aumenta a frequência cardíaca"
   Target_zh_cn "提高心率"
   Target_uk_ua "Підвищує частоту серцевих скорочень"
   Modified 1725500676
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55BA0A3E335}" {
   Id "ACE_Medical-InfoWidget_Metoprolol"
   Target_en_us "Decreases heart rate"
   Target_de_de "Sinkt die Herzfrequenz"
   Target_pt_br "Reduz a frequência cardíaca"
   Target_zh_cn "降低心率"
   Target_uk_ua "Знижує частоту серцевих скорочень"
   Modified 1725500698
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55BA77C7538}" {
   Id "ACE_Medical-InfoWidget_Naloxone"
   Target_en_us "Antagonist for opioids like morphine"
   Target_de_de "Antagonist für Opioide wie Morphin"
   Target_pt_br "Antagonista para opioides como morfina"
   Target_zh_cn "對嗎啡等鴉片類藥物的拮抗劑"
   Target_uk_ua "Застосовується при передозуванні"
   Modified 1725500749
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55BB2295B31}" {
   Id "ACE_Medical-InfoWidget_Phenylephrine"
   Target_en_us "Increases blood pressure and slows down bleeding and transfusion"
   Target_de_de "Erhöht den Blutdrucks und verlangsamt Blutung und Transfusion"
   Target_pt_br "Aumenta a pressão arterial e diminui o sangramento e transfusão"
   Target_zh_cn "提高血壓，並減緩出血與輸血速度"
   Target_uk_ua "Підвищує артеріальний тиск"
   Modified 1725500793
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5586006E639}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Description"
   Target_en_us "Administered to unconscious patients."
   Target_de_de "Verabreicht an bewusstlose Patienten."
   Target_pt_br "Administrado a pacientes inconscientes."
   Target_zh_cn "給予無意識患者使用"
   Target_uk_ua "Застосовується до непритомних пацієнтів, УВАГА застосовувати при нормальних показниках ЧСС (близько 70 ударів на секунду) та Артеріальному тиску близько 120/80 "
   Modified 1725500824
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5586D87363C}" {
   Id "ACE_Medical-Item_AmmoniumCarbonate_Name"
   Target_en_us "Ammonium Carbonate"
   Target_de_de "Ammoniumcarbonat"
   Target_pt_br "Carbonato de Amônio"
   Target_zh_cn "碳酸銨 (嗅鹽)"
   Target_uk_ua "Амонію карбонат (нюхальна сіль)"
   Modified 1725500240
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55B9B65D93A}" {
   Id "ACE_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to patients in cardiac arrest"
   Target_de_de "Verabreicht an Patienten mit Herzstillstand"
   Target_pt_br "Administrado a pacientes em parada cardíaca"
   Target_zh_cn "給予心臟驟停的患者使用"
   Target_uk_ua "Застосовується при зупинці серця"
   Modified 1725500893
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{65C6FCD64D6EB190}" {
   Id "ACE_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine"
   Target_de_de "Epinephrin"
   Target_zh_cn "腎上腺素"
   Target_uk_ua "Адреналін (Епінефрин)"
   Modified 1725499874
   Author "PC Ill"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5585D442A6C}" {
   Id "ACE_Medical-Item_Metoprolol_Description"
   Target_en_us "Administered to patients with too high heart rate"
   Target_de_de "Verabreicht an Patienten mit überhöhter Herzfrequenz"
   Target_pt_br "Administrado a pacientes com frequência cardíaca muito alta"
   Target_zh_cn "給予心率過高的患者使用"
   Target_uk_ua "Застосовується при занадто високому пульсі"
   Modified 1725500917
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5585EEF5D9C}" {
   Id "ACE_Medical-Item_Metoprolol_Name"
   Target_en_us "Metoprolol"
   Target_de_de "Metoprolol"
   Target_pt_br "Metoprolol"
   Target_zh_cn "美托洛爾 (Metoprolol)"
   Target_uk_ua "Метопролол"
   Modified 1725500086
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5582C95F2EA}" {
   Id "ACE_Medical-Item_Naloxone_Description"
   Target_en_us "Administered to patients with opioid overdose"
   Target_de_de "Verabreicht an Patienten mit Opioidüberdosis"
   Target_pt_br "Administrado a pacientes com overdose de opioides"
   Target_zh_cn "給予鴉片類藥物過量的患者使用"
   Target_uk_ua "Застосовується при передозуванні опіоїдами"
   Modified 1725500987
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B558202D6005}" {
   Id "ACE_Medical-Item_Naloxone_Name"
   Target_en_us "Naloxone"
   Target_de_de "Naloxon"
   Target_pt_br "Naloxona"
   Target_zh_cn "納洛酮 (Naloxone)"
   Target_uk_ua "Налоксон"
   Modified 1725500078
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55877861E3A}" {
   Id "ACE_Medical-Item_Phenylephrine_Description"
   Target_en_us "Administered to patients for raising blood pressure"
   Target_de_de "Verabreicht an Patienten um den Blutdruck zu erhöhen"
   Target_pt_br "Administrado a pacientes para elevar a pressão arterial"
   Target_zh_cn "給予因低血壓需要升壓的患者使用"
   Target_uk_ua "Застосовується для підвищення тиску"
   Modified 1725501050
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55875DE022F}" {
   Id "ACE_Medical-Item_Phenylephrine_Name"
   Target_en_us "Phenylephrine"
   Target_de_de "Phenylephrin"
   Target_pt_br "Fenilefrina"
   Target_zh_cn "苯福林 (Phenylephrine)"
   Target_uk_ua "Фенілефрин"
   Modified 1725500277
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55ED01FBD98}" {
   Id "ACE_Medical-MetoprololInjectionAction"
   Target_en_us "Inject metoprolol"
   Target_de_de "Metoprolol injizieren"
   Target_pt_br "Injetar metoprolol"
   Target_zh_cn "注射美托洛爾 (Metoprolol)"
   Target_uk_ua "Ввести метопролол"
   Modified 1725501105
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55ECF6624E9}" {
   Id "ACE_Medical-NaloxoneInjectionAction"
   Target_en_us "Inject naloxone"
   Target_de_de "Naloxon injizieren"
   Target_pt_br "Injetar naloxona"
   Target_zh_cn "注射納洛酮 (Naloxone)"
   Target_uk_ua "Ввести налоксон"
   Modified 1725501121
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55235D38AF1}" {
   Id "ACE_Medical-Notification_BLOOD_PRESSURE_RESULT"
   Target_en_us "You find a blood pressure of %1/%2 mmHg"
   Target_de_de "Der Blutdruck liegt bei %1/%2 mmHg"
   Target_pt_br "pressão arterial em %1/%2 mmHg"
   Target_zh_cn "你測得的血壓為 %1/%2 mmHg"
   Target_uk_ua "У пацієнта тиск %1/%2 мм рт.ст."
   Modified 1725501164
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B5523F76CF1E}" {
   Id "ACE_Medical-Notification_PULSE_RESULT"
   Target_en_us "You find a heart rate of %1"
   Target_de_de "Herzfrequenz ist %1"
   Target_pt_br "Frequência cardíaca em %1"
   Target_zh_cn "你測得的心律為 %1"
   Target_uk_ua "У пацієнта пульс %1"
   Modified 1725501458
   Author "Kexanone"
   LastChanged "YuanYu"
  }
  CustomStringTableItem "{6228B55ED9DB4B14}" {
   Id "ACE_Medical-PhenylephrineInjectionAction"
   Target_en_us "Inject phenylephrine"
   Target_de_de "Phenylephrin injizieren"
   Target_pt_br "Injetar fenilefrina"
   Target_zh_cn "注射苯福林 (Phenylephrine)"
   Target_uk_ua "Ввести фенілефрин"
   Modified 1725501134
   Author "Kexanone"
   LastChanged "YuanYu"
  }
 }
}
