SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69B604869DAB86EF}" {
     m_sEntityPrefab "{3DD5351CFB98FC7F}Prefabs/Items/Equipment/MineDetector/ACE_MineDetector_VMM3.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69B419EA8D15FDCE}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69BB04678AEDDC95}" {
     m_sEntityPrefab "{619F4A05EE0F4105}Prefabs/Items/Equipment/Detonators/ACE_DeadManSwitch.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69BB04678AED033E}" {
       m_eItemType EXPLOSIVES
       m_iSupplyCost 15
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}