SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69B604869DAB86EF}" {
     m_sEntityPrefab "{3DD5351CFB98FC7F}Prefabs/Items/Equipment/MineDetector/ACE_MineDetector_VMM3.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69B419EA8D15FDCE}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}