name: Docs

on:
  push:
    branches: [master, release]
    paths: ['docs/**']
  pull_request:
    paths: ['docs/**']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: withastro/action@v2
        with:
          path: docs
