name: Build docs

on:
  push:
    branches: [master, release]
    paths: [/docs]
  pull_request:
    paths: [/docs]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: withastro/action@v2
